### ISSUE TITLE
how to set up a local env without Google Cloud

### ISSUE THREAD

**Issue by chrischjh** [HTTPArchive/httparchive.org#107]
HI, I'm working on some enterprise systems which can only be accessed internally, how to set up an httparchive private instance in Linux or Windows? It may work perfectly with WPT private instance. Thanks a lot

**Comment by rviscomi** [comment]
Hi @chrischjh. Can you elaborate on what kind of data you're looking to collect using HTTP Archive? 

It sounds like you want to build your own version of HA to run on a local network with a private instance of WPT. All of the WPT controlling logic is in https://github.com/HTTPArchive/legacy.httparchive.org. You may find what you're looking for in that repository. 

Alternatively, you may be interested in building something custom and lightweight for yourself. Ask the users on the [WPT Private Instance forum](https://www.webpagetest.org/forums/forumdisplay.php?fid=12) for ideas.

**Comment by chrischjh** [comment]
Hi @rviscomi , thanks for your reply. Yes I'm trying to build an internal webperf test and monitoring platform, I've managed to bring up a WPT private instance and have been running some testing on it, I want to monitor the trends of various webperf metrics for our internal applications over time, and explore more performance analysis based on the data collected. I wanted to build an application to do so, but httparchive.org looks really awsome, thus trying to study if I can set up a private one and leverage the great power. Thanks a lot

**Comment by rviscomi** [comment]
Building a local version of HTTP Archive might be overkill for your use case. We specialize in scaling up to 1+ million web pages and aggregating the massive amounts of data. You're welcome to fork our code and repurpose it for your use case, but I'd recommend something more lightweight if you can build/find it.
