### ISSUE TITLE
Add color contrast metric from LH a11y audit

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#111]
Related to #94, add on to the report with other metrics like color contrast. (The audit ID is `color-contrast`)

cc @tkadlec

**Comment by wellingguzman** [comment]
To add a new metric requires to have the query that creates the report, correct? Is the report already created or it needs to be created? I checked the queries on `BigQuery` repo, and didn't find any related to color contrast metric.

Also hard to mess around with the BigQuery dataset, as it takes a while to process.
