### ISSUE TITLE
Track JS library usage

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#113]
Build a new custom timeseries visualization in the State of JS report that tracks usage of popular JS libraries.

I imagine this being a line chart with one line per library. We'd need to override the default Highcharts color scheme to give each line a distinct color. Right now it's set up for desktop and mobile series.

We also need to specially handle jQuery somehow. Its usage is so much higher than everything else so it would make everything else look tiny by comparison. We can enable y-axis zooming, use an exponential y-axis, or rely on manually toggling the series on/off and letting the chart autoscale.

**Comment by developit** [comment]
Exponential axis would be my preference for this.

**Comment by tjmonsi** [comment]
I just want to check up on this. I just want to know how many libraries should this line graph show? top 20? top 50? with a lot of libraries out there (and some of them packaged and bundled in large JS apps, how should it work?

**Comment by rviscomi** [comment]
This is resolved by the JavaScript chapter of the Web Almanac at annual granularity. Not ideal but we're getting the data published.
