### ISSUE TITLE
Fix color contrast of navigation links on hover

### ISSUE THREAD

**Issue by xi** [HTTPArchive/httparchive.org#115]
I noticed that the color contrast on `nav li:hover` is way to low (https://contrast-ratio.com/#white-on-%23bcced1). There might be other places where this is an issue. 

I could help with that, but I did not create a pull request since design/branding changes are always controversial.

**Comment by rviscomi** [comment]
Thanks @xi. No strong design/branding concerns. Feel free to open a PR.
