### ISSUE TITLE
Improve App Engine's caching of report metadata

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#120]
Today while updating the CrUX report to the latest dataset, the website did not show 2019_12_01 as an available option.

The [get_latest_date](https://github.com/HTTPArchive/httparchive.org/blob/master/reports.py#L95-L104) function caches the most recent date in Cloud Storage for a given metric, which is how we minimize lookups in GCS. It's supposed to be cached for up to 3 hours, but it was 12+ hours before I manually restarted the GAE instance for the new date to become available.

Investigate why the cache isn't working as expected and explore using supported alternatives like Memcache rather than a homegrown solution.

**Comment by tunetheweb** [comment]
I believe this was fixed in #339 so closing.
