### ISSUE TITLE
Create a random sample set for the latest of each BigQuery dataset

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#121]
The BQ tables are getting unwieldy and expensive to query. We use scheduled queries to generate the tables in the `latest` dataset. Similarly, we should generate a subset of these tables randomly limited to some number of rows to ensure that the query will be inexpensive. For the `requests` dataset we should group by `page` so that all pages in the sample have all of their respective requests.

- [ ] calculate the average row size in bytes for each dataset
- [ ] pick a sample size in rows corresponding to about 1 GB per dataset (this can change)
- [ ] schedule a query for each dataset (requests, pages, etc) and each client (desktop, mobile) to materialize sample tables

**Comment by max-ostapenko** [comment]
@rviscomi Does the sample_data check all the boxes?

**Comment by tunetheweb** [comment]
Yes, so think we can close this.
