### ISSUE TITLE
Missing recent summary_requests tables

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#122]
According to the [BQ Meta Dashboard](https://datastudio.google.com/open/1jh_ScPlCIbSYTf2r2Y6EftqmX9SQy4Gn), the summary_requests dataset is missing several tables:

![image](https://user-images.githubusercontent.com/1120896/51270942-3fef1c80-1994-11e9-9e89-e22af37dc974.png)

- [ ] 2016_01_01_desktop
- [ ] 2016_01_15_desktop
- [ ] 2016_12_15_desktop (partial)
- [ ] 2016_12_15_mobile
- [ ] 2017_01_01_desktop
- [ ] 2017_01_15_desktop
- [ ] 2017_11_15_mobile
- [ ] 2018_08_15_mobile
- [ ] 2018_11_01_mobile
- [ ] 2018_12_01_desktop
- [ ] 2018_12_01_mobile

We need to rerun `sync_csv.sh` for these dates and distinguish between irrecoverable data loss and fixable parsing errors.

**Comment by max-ostapenko** [comment]
@rviscomi @paulcalvano is it possible to recover today? Before I run the backfill.
Or we leave it?
