### ISSUE TITLE
Recent response_bodies tables have been shrinking

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#123]
According to the [BQ Meta Dashboard](https://datastudio.google.com/open/1jh_ScPlCIbSYTf2r2Y6EftqmX9SQy4Gn), the response_bodies dataset tables have some anomalies:

![image](https://user-images.githubusercontent.com/1120896/51272100-2e5b4400-1997-11e9-93d5-97e25675a702.png)

- [x] on 2018_10_15 and 2018_12_01 the number of rows in the mobile tables dropped
  - the 2018_12_15 mobile table shows an increase in rows but still below pre-October levels
- [x] on 2018_10_15 the number of rows in the desktop table dropped

**Comment by pmeenan** [comment]
Mobile had the known-problem with lighthouse that was fixed recently. I'd expect to see a massive jump with the Jan 1 crawl.

**Comment by pmeenan** [comment]
Specificall, [this](https://github.com/WPO-Foundation/wptagent/commit/3ceb7fef81dc8ad59274a21b8d92af6897503344) change from December 21st should fix it.

**Comment by rviscomi** [comment]
That just made me realize that we don't have a page for Lighthouse metadata in the dashboard... just added that:

![image](https://user-images.githubusercontent.com/1120896/51272888-5d72b500-1999-11e9-85f5-a438bf139243.png)

There doesn't actually seem to be a significant loss of LH data, but good to know there was a known issue that got fixed.

In any case, I think that would be tangential to the response_bodies issue, which seems to be that we're not capturing as many response bodies per page as usual.

**Comment by pmeenan** [comment]
Yes, sorry - the problem was that for mobile tests we run the normal test and then make a pass for lighthouse. In the lighthouse pass we were deleting the bodies from the original test. That's why it was impacting mobile only. It's not directly related to lighthouse itself, just how the agent collects the data.

**Comment by rviscomi** [comment]
Ah ok thanks for explaining. Still curious about the 10% drop in desktop response bodies though.

**Comment by rviscomi** [comment]
Closing this issue. The data is irrecoverable but has been corrected as of the 2019_01_01 crawl.

![image](https://user-images.githubusercontent.com/1120896/52430422-05305e00-2ad4-11e9-9238-b681983dd0d3.png)
