### ISSUE TITLE
Track better compression across the web

### ISSUE THREAD

**Issue by kuettel** [HTTPArchive/httparchive.org#124]
To accelerate (and track) the adoption of better compression across the web, it would be most helpful if HTTP Archive could track supported compression methods.  Specifically, tracking the set of sites which are served with Brotli compression (content-encoding:br) vs. gzip.

https://opensource.googleblog.com/2015/09/introducing-brotli-new-compression.html
https://www.gstatic.com/b/brotlidocs/brotli-2015-09-22.pdf

Thank you!

**Comment by rviscomi** [comment]
Closing this as we have annual Compression reports now in the Web Almanac, eg https://almanac.httparchive.org/en/2019/compression
