### ISSUE TITLE
Categorize origins

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#125]
Group origins by category/vertical, for example news/travel/etc. This will enable category deep dives and comparisons.

[DMOZ](http://www.dmoz.org/) is no longer operational but a recent data dump is available. We should look for alternate sources.

Slightly related: https://github.com/HTTPArchive/httparchive/issues/75. Alexa is deprecating their top 1M ranking, so finding a rank+category solution would be a bonus.

**Comment by max-ostapenko** [comment]
Origin category/rank is available using [Topics API categorization](https://console.cloud.google.com/bigquery?authuser=7&project=httparchive&ws=!1m15!1m4!4m3!1shttparchive!2sresponse_bodies!3s2024_09_01_mobile!1m4!6m3!1shttparchive!2sfn!3sGET_HOST_CATEGORIES!1m4!4m3!1shttparchive!2sall!3srequests).
