### ISSUE TITLE
Reconfigure mobile testing to use 4G speeds

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#126]
Data from the Chrome UX Report indicates that the vast majority of connection speeds on mobile devices (phone/tablet) are effectively 4G:

```sql
#standardSQL
SELECT
  SUM(IF(effective_connection_type.name = '4G', bin.density, 0)) / SUM(bin.density) AS pct_mobile_4g
FROM 
  `chrome-ux-report.chrome_ux_report.201710`,
  UNNEST(first_contentful_paint.histogram.bin) AS bin
WHERE
  form_factor.name IN ('phone', 'tablet')
```

https://bigquery.cloud.google.com/results/chrome-ux-report:bquijob_35020ffa_160510ab375

**Result:** 87.95%

Update the WebPageTest configuration for mobile tests to use 4G speeds to more accurately represent real user conditions.

**Comment by rviscomi** [comment]
Updated query and results based on the January 2019 CrUX dataset:

```sql
#standardSQL
SELECT
  SUM(IF(effective_connection_type.name = '4G', bin.density, 0)) / SUM(bin.density) AS pct_mobile_4g
FROM 
  `chrome-ux-report.all.201901`,
  UNNEST(first_contentful_paint.histogram.bin) AS bin
WHERE
  form_factor.name IN ('phone', 'tablet')
```

91.8%. Keep in mind this is an average density across ~4M origins.

**Comment by pmeenan** [comment]
FWIW, "4G" in effective connection type just means RTT < 270ms and bandwidth > 700Kbps. It's a pretty low threshold.

The WPT "3G" connection profile is 300ms latency and 1.6Mbps bandwidth and the "3G Fast" is 150ms RTT (well into the "4G" range.  The lighthouse runs use the "3G Fast" profile as that is what they were calibrated against for scoring. I believe HA uses "3G" for the mobile runs (I'm happy to switch to 3G Fast if that is the case and at least match the lighthouse config).

**Comment by josephscott** [comment]
Are there other large data sets that confirm these numbers?  I'm concerned about making an opt in set of data points equal to the real world without other data sets pointing the same direction.

**Comment by igrigorik** [comment]
@josephscott we sanity checked CrUX telemetry against internal speed data at Google for a number of our properties, and it lined up ~closely. Similarly, @paulcalvano corroborated same results on his end as well — Paul, please jump in here if I'm misrepresenting. As such, while I acknowledge that CrUX has population biases, I trust the results and believe they accurately represent real-world user experience of Chrome users.

**Comment by tunetheweb** [comment]
Closing as use 4G for WPT runs now.
