### ISSUE TITLE
Update the FAQ about where HA gets its URLs

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#129]
The FAQ [How does the HTTP Archive decide which URLs to test?](https://httparchive.org/faq#how-does-the-http-archive-decide-which-urls-to-test) is outdated. Rather than intersecting CrUX with Alexa crawling twice a month now we simply crawl all CrUX URLs monthly.

**Comment by mathiasbynens** [comment]
Ref. https://discuss.httparchive.org/t/use-tranco-list-instead-of-alexa-top-1m/1581/2
