### ISSUE TITLE
Use rel=nofollow on sponsor links

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#132]
To avoid the impression that sponsors get SEO benefits for supporting the HTTP Archive, we should apply `rel="nofollow"` to all outbound sponsor links.

**Comment by tjmonsi** [comment]
@rviscomi i'll take this.

**Comment by tjmonsi** [comment]
@rviscomi  you're welcome. I do want to work on the other stuff but I don't know yet how to contribute (like querying data or thinking of signals). I'm still new at using BigQuery so I am going to read first how things work out here (on getting data to show on the frontend). If there are needed changes again on the frontend, just ping me 😄
