### ISSUE TITLE
Consider enabling `Sec-Fetch-Dest`.

### ISSUE THREAD

**Issue by mikewest** [HTTPArchive/httparchive.org#136]
The `Sec-Fetch-Dest` header exposes the "[destination](https://fetch.spec.whatwg.org/#concept-request-destination)" of a request, which can be quite useful in tracking down things associated with particular kinds of requests that aren't otherwise distinguishable by the `Accept` header (script loads, for instance). While we're debating whether it actually produces a reasonable security boundary in mikewest/sec-metadata#16, it seems like it would produce some interesting data in the archive that would enable us to make finer-grained decisions about things related to particular request types.

For instance, I'd love to figure out which `<script>` requests have unreasonable MIME types. So I can block them by default. :)

The feature can be enabled via [Chromium's `SecMetadata` feature flag](https://cs.chromium.org/chromium/src/content/public/common/content_features.cc?rcl=011f16a1f7dd125b7a97a5aa2514826a2fa6bd14&l=417).

WDYT?

**Comment by rviscomi** [comment]
I'm generally in favor of improving our telemetry.

@pmeenan is this something you can implement in the WPT agents? and is this a change that can take effect for most of the April tests or would it have to wait until May?

**Comment by rviscomi** [comment]
🛎 @pmeenan ?

**Comment by pmeenan** [comment]
Sorry, took me a bit to see how to turn on the features through the command-line (was easier than I thought). Testing it now.

**Comment by pmeenan** [comment]
Just enabled it by default for WebPageTest.  It will be available on the public instance over the next hour and will be enabled for the May crawl.  Here is an example from my dev environment: https://www.webpagetest.org/result/190425_TxYG_470cd369d8110c606538d6962d73248b/1/details/#step1_request2

**Comment by rviscomi** [comment]
Great thanks for looking into it!

**Comment by mikewest** [comment]
Thank you both! This is enabling some interesting analysis in https://github.com/whatwg/html/issues/3255#issuecomment-496438581 and elsewhere. :)

**Comment by pmeenan** [comment]
Awesome. Fwiw, the header will also help with cloudflare's http/2
server-side prioritization work. As it gets more broadly adopted.
