### ISSUE TITLE
Enable the Layout Jank API in WPT agents and surface data in HARs

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#142]
The goal is to improve our telemetry of web pages' layout stability. There's an experimental API (in origin trial and behind a flag) that surfaces the % of the viewport that changes (aka "janks") due to layout changes.

Per https://github.com/GoogleChrome/OriginTrials/issues/53#issuecomment-488367187 we can pass `--enable-blink-features=LayoutInstabilityAPI` on the command line to enable it.

Not sure what else we need to do to get the output in the HAR files. @pmeenan will it automatically appear in the BlinkFeatures object? We might also want to consider a custom metric to aggregate the data, as the output might be noisy.

- [x] enable the API in WPT
- [x] add a custom metric to WPT to calculate CLS

**Comment by pmeenan** [comment]
Does the layout jank API have an underlying trace event (or arg) on the layout events that gets recorded normally? If there is a blink trace event with the % viewport layout change (I know the number of elements is already recorded). we can just pull those directly. We don't need a javascript-exposed API to collect the data.

**Comment by rviscomi** [comment]
Paging @skobes

**Comment by skobes** [comment]
Yes there is a trace event called FrameLayoutJank.

https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/layout/jank_tracker.cc?q=TRACE_EVENT

**Comment by rviscomi** [comment]
Related https://dev.to/chromiumdev/measuring-cumulative-layout-shift-cls-in-webpagetest-5cle

**Comment by pmeenan** [comment]
Are we adding it to the crawl? (i.e. do I need to add the command-line flag so you can use a custom metric to collect it)

**Comment by rviscomi** [comment]
Yes if you could set `--enable-blink-features=LayoutInstabilityAPI` that would allow us to measure CLS as a custom metric when M77 becomes available.

**Comment by pmeenan** [comment]
Done. Try it out on WPT after an hour (so they can update) to make sure it is working as expected.

**Comment by rviscomi** [comment]
Thanks @pmeenan! Ran a test on Canary with a custom metric (without specifying the flag) and [it works](https://webpagetest.org/custom_metrics.php?test=190731_2G_d06c4c083d3d25f75220b803fe9f977d&run=1&cached=0)!

The next step for this issue is to implement the custom metric on the HA side.

**Comment by rviscomi** [comment]
CLS is now available in WPT so we can close this issue
