### ISSUE TITLE
What should we add to our FAQ?

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#144]
We should be keeping our FAQ up to date with the things people are actually curious about.

Today I got questions like these:

> Are the Lighthouse tests run on real devices?

They're run on VMs that use mobile emulation and throttling.

> Are the Lighthouse tests run at the same time as the rest of the crawl?

They're run in parallel to the traditional WebPageTest runs.

> How are the URLs selected?

URLs are the root/home pages for origins in the most recent release of the Chrome UX Report. We segment by desktop and mobile using the form_factor dimension, so that mobile URLs correspond to actual origins visited by phones.

What other questions would be good to include/update?

**Comment by anoblet** [comment]
How are the metrics chosen?
