### ISSUE TITLE
Modernize to Python 3 App Engine environment

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#169]
See https://cloud.google.com/appengine/docs/standard/python3/python-differences (though we're using the flexible environment)

Python 2 is reaching its end of life in 2020: https://pythonclock.org/

**Comment by anoblet** [comment]
I was able to get reports running on v3 by changing https://github.com/HTTPArchive/httparchive.org/blob/b87394873bdf7d569bc0a4190fae16a8cb0d4234/reports.py#L64 to:
```
report['metrics'] = list(map(get_metric, report.get('metrics')))
```

**Comment by rviscomi** [comment]
Duplicate: #190
