### ISSUE TITLE
Webpack and Python do not run in parallel on Windows

### ISSUE THREAD

**Issue by anoblet** [HTTPArchive/httparchive.org#171]
`npm run watch & python main.py` doesn't run in parallel on Windows.

**Comment by rviscomi** [comment]
They're intended to run sequentially. Is the Python part running for you at all?

**Comment by anoblet** [comment]
It is, I was just documenting that when I run `npm run start` that webpack runs, though python doesn't. I need to run them in separate shells.

**Comment by rviscomi** [comment]
Ah ok. Do you know of a Windows-friendly alternative to `&&`?

**Comment by anoblet** [comment]
It should work.. I'm not entirely sure why it doesn't :/

**Comment by anoblet** [comment]
I actually ran into this in the pre webpack-dev-server days using webpack --watch with browserify. The only solution I could find was to use `npm-run-all`. I don't think it's

**Comment by anoblet** [comment]
I feel comfortable closing this if you do. The issue is here for reference for us windows devs :)

**Comment by rviscomi** [comment]
Before we close it, could you add a note to the README for other Windows devs who might run into similar issues? For example, "Windows users: run watch and server commands separately."

**Comment by rviscomi** [comment]
Closed by #172
