### ISSUE TITLE
Link to the Web Almanac

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#173]
Even while it's under development, it'd be good to add a link to https://almanac.httparchive.org to make it discoverable to users and search engines. Could be added to the top nav.

**Comment by anoblet** [comment]
Should this be first level? Should it be at the top or bottom of a second level? I'm able to take care of this.

**Comment by rviscomi** [comment]
Thanks @anoblet! First level link would be great. Maybe between "Discuss" and "About" in both the header and footer.
