### ISSUE TITLE
2019-08-01 desktop contains suspicious timing data

### ISSUE THREAD

**Issue by Themanwithoutaplan** [HTTPArchive/httparchive.org#180]
In one of my reports I've started seeing extremely low values for "onLoad". This isn't a perfect metric but it does have the advantage of being long-established.
I see over 800,000 websites with an onLoad of less than 100ms. For mobile it's only about 140, which is negligible.

Is any other data (URLs or test id's) required?

**Comment by Themanwithoutaplan** [comment]
As zip because GitHub :-/
[2019-01-01-onload.zip](https://github.com/HTTPArchive/httparchive.org/files/3552148/2019-01-01-onload.zip)
Sorry, off by factor 10 in my count but here are all the tests with "onLoad" < 1000. "visualComplete" provided for quick correlation.

**Comment by Themanwithoutaplan** [comment]
Here's a few. I import into Postgres from the CSV dumps so there's always a chance that I've got something wrong there but these do tally with individual reports on legacy.httparchive.org

wptid | onLoad | visualComplete
-- | -- | --
190803_DxD_SGY | 1 | 9700
190818_DxM_18C9 | 1 | 21200
190817_Dx4C_8HPQ | 1 | 9600
190811_Dx2R_5CNB | 1 | 35500
190815_Dx4S_9C5D | 1 | 10600
190805_Dx10_1YKN | 1 | 5600
190815_Dx2K_52C6 | 1 | 6800
190815_Dx1T_3J4Q | 1 | 3000
190808_Dx3N_75FN | 1 | 16000
190815_Dx9_K76 | 1 | 7800
190807_Dx73_DWXM | 1 | 8800
190813_Dx40_7TH5 | 1 | 6000
190817_Dx3X_7P07 | 1 | 5000
190806_Dx2Q_5A8P | 1 | 7000
190812_Dx34_64ED | 1 | 4600
190804_Dx6K_CWT8 | 1 | 24600
190801_Dx43_80HX | 1 | 26200
190805_Dx3H_6WSP | 1 | 38400
190802_Dx2V_5JNE | 1 | 7200
190809_Dx5J_AW8Y | 1 | 7800
190813_DxX_1S9T | 1 | 7200
190806_Dx6_DHB | 1 | 5100
190803_Dx1A_2JD5 | 1 | 14100
190805_Dx2P_58D4 | 1 | 19900
190811_Dx1W_3NJQ | 1 | 60000
190802_Dx3G_6V50 | 1 | 3200
190810_Dx3H_6WZE | 1 | 15000
190808_Dx4Z_9Q0N | 1 | 12400
190809_Dx7N_EYNW | 1 | 10500
190806_Dx1K_35E3 | 1 | 6800
190817_Dx4C_8JR8 | 1 | 6200
190804_DxG_108V | 1 | 6700
190806_Dx4X_9KK2 | 1 | 8500
190807_Dx59_ABAP | 1 | 26000
190805_Dx4Y_9N8G | 1 | 15500
190815_Dx9_JER | 1 | 9400
190801_Dx76_E2TN | 1 | 12900
190804_Dx2A_4J0Y | 1 | 4700
190807_Dx69_CA6B | 1 | 15000
190802_Dx1Q_3BJN | 1 | 5200
190806_Dx3E_6RMG | 1 | 6600
190814_Dx6W_DEKK | 1 | 8700
190815_Dx56_A5JR | 1 | 9000

**Comment by Themanwithoutaplan** [comment]
Great to know the root cause was identified elsewhere and has already been fixed.

For clarity, is there anyway we can identify all the relevant tests? Is it possible to get the correct information from the HAR files?

**Comment by pmeenan** [comment]
You can probably compare loadTime to loadEventStart and come up with a heuristic. i.e. 

if loadTime < 1000 && (loadEventStart - loadTime) > (loadEventStart * 0.5)

For the cases where it is invalid you can substitute loadEventStart.

**Comment by Themanwithoutaplan** [comment]
`loadEventStart` isn't in the CSV dump IIRC, so this would have to come from the HAR, right?

**Comment by pmeenan** [comment]
Right
