### ISSUE TITLE
"_quirks_mode" metric is always false

### ISSUE THREAD

**Issue by zcorpan** [HTTPArchive/httparchive.org#186]
In https://github.com/HTTPArchive/legacy.httparchive.org/pull/58 we introduced a custom metric to record `document.compatMode`. I *think* it has been working in the past, but now it appears to be `false` for all pages.

```
SELECT url FROM `httparchive.pages.2019_11_01_desktop` WHERE STRPOS(payload, '"_quirks_mode":false') > 0
```
Lots of results.
```
SELECT url FROM `httparchive.pages.2019_11_01_desktop` WHERE STRPOS(payload, '"_quirks_mode":true') > 0
```
No results.

I wanted this metric now to research https://github.com/whatwg/quirks/issues/48 😐

**Comment by rviscomi** [comment]
Are there any example pages that return `BackCompat` that we can test this with? Are there other methods of detecting quirks mode, like the doctype, that can be parsed from the HTML body?

**Comment by zcorpan** [comment]
https://github.com/HTTPArchive/legacy.httparchive.org/issues/40#issuecomment-187264991 has a query that still works with newer dataset.

I ran it now on  `httparchive.pages.2019_11_01_desktop` resulting in 209,037 pages.

https://docs.google.com/spreadsheets/d/14-44npYPWVgdPQyMzIhdfD1m3UTEsqOSnH93rPNHbi4/edit?usp=sharing

**Comment by zcorpan** [comment]
I think that result misses out pages that have no doctype at all.

Running a query for `WHERE doctype IS NULL` gives only 39 results, which seems *way* too low to represent the number of pages without a doctype.

**Comment by zcorpan** [comment]
No wait, there's a whole bunch of rows with `""` which probably means no doctype.

**Comment by rviscomi** [comment]
@zcorpan can we close this?

**Comment by zcorpan** [comment]
No, we should either fix the metric so it works again or remove it.

The original implementation is here

https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/quirks_mode.js

That repo is now marked legacy. Should it be moved somewhere else?

**Comment by rviscomi** [comment]
Here's a query that looks at all values of the custom metric:

```sql
SELECT
  JSON_EXTRACT(payload, '$._quirks_mode') AS q,
  COUNT(0) AS n
FROM
  `httparchive.pages.2020_06_01_mobile`
GROUP BY
  q
```

q | n
-- | --
  | 100
1 | 238849
false | 5494475

For some reason the JSON encoding of `true` is being converted to `1`, but according to these results it does seem like there are some pages that are in quirks mode.

**Comment by zcorpan** [comment]
Ooh, so it is working then. Great! Thanks @rviscomi

**Comment by zcorpan** [comment]
So per this metric, ~4.17% of pages are in quirks mode.
