### ISSUE TITLE
2019_12_01 data missing

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#187]
![image](https://user-images.githubusercontent.com/1120896/71849486-290f7180-30a0-11ea-8384-459999ec6654.png)

The December dataset should be available by now but the [monitoring dashboard](https://datastudio.google.com/s/l5cFY9EvlFM) is showing a very small amount of mobile data and no desktop data at all.

**Comment by brendankenny** [comment]
Any news about this @rviscomi? Seems like the amount of mobile data is back to normal in the dashboard now, though still no desktop data?

I noticed the `httparchive.lighthouse.2019_12_01_mobile` data is ~1/3 of its typical size on disk and number of rows, and it was written on Dec 6th instead of nearer the end of the month like it usually is. I haven't looked into if the data that is there is good, though.

cc @paulirish if you're still gathering metric numbers

**Comment by rviscomi** [comment]
I've deleted the partial mobile HAR tables from BigQuery (everything not prefixed with summary_*) including the partial 2020_01 desktop tables.

The December desktop HAR tables are currently being regenerated (4 hours elapsed) and should be available soon. I'll do the same for the mobile HAR tables tomorrow.

As for the CSV tables (summary_*) the mobile data all seems to be intact. I'm unable to find a complete backup of the desktop data. We've regenerated this using HAR data before, but it'd be great to do this the easy way using CSVs if possible. I'll keep looking.

**Comment by krgovind** [comment]
Thanks Rick! FYI, there seem to be two sets of December desktop tables in BigQuery: 2019_12_01desktop and 2019_12_01_desktop. The former appears to have about half the number of entries as the latter.

**Comment by rviscomi** [comment]
Ah yes, good catch. I've corrected the naming of the tables so everything except summary_*_desktop should be back to normal now.

![image](https://user-images.githubusercontent.com/1120896/72173241-19946f00-33a5-11ea-9713-01c1bcb3d3f4.png)

**Comment by rviscomi** [comment]
Ok I think I've found the backups: `http://ia801501.us.archive.org/34/items/httparchive_downloads_Dec_5_2019/httparchive_Dec_5_2019_requests.
csv.gz`. The file is enormous and it's taking about 5 hours to download at ~4Mbps. I'll work on regenerating the desktop summary tables this weekend and update this thread when it's available.

**Comment by brendankenny** [comment]
Thanks @rviscomi!

**Comment by rviscomi** [comment]
The December dataset should be fully available now.

![image](https://user-images.githubusercontent.com/1120896/72300689-807a8800-3632-11ea-9502-9750fa10e9cf.png)

![image](https://user-images.githubusercontent.com/1120896/72300872-0bf41900-3633-11ea-866b-66f84d355452.png)
