### ISSUE TITLE
Cookie values missing from recent runs

### ISSUE THREAD

**Issue by paulcalvano** [HTTPArchive/httparchive.org#193]
It seems that starting with the September 2019 run, cookies were stripped from the WebPageTest results due to a change in the required net-log command line argruments, resulting in the a message such as "[x bytes were stripped]" being stored in place of ~85% of all cookies values.

The commands line argument used in wptagent was updated by @pmeenan . I'm just opening this issue as a reminder to check the cookie data in next month's data.

**Comment by rviscomi** [comment]
This came up again in https://discuss.httparchive.org/t/does-bigquery-contain-har-archive-or-cookies-of-crawled-webpages/1968/3?u=rviscomi. I found it present on 30% of cookies as of the June dataset. We should check the July data to confirm the fix.

**Comment by tunetheweb** [comment]
Closing as per the above thread. I reran the query for June 2021 and still at 1.44%.
