### ISSUE TITLE
Investigate missing CSS blink features

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#194]
For example: https://chromestatus.com/metrics/css/timeline/popularity/516

![image](https://user-images.githubusercontent.com/1120896/72637866-3514f200-3930-11ea-9665-29f31b5f54f6.png)

The `pages` HAR dataset does include a `_blinkFeatureFirstUsed.CSSFeatures` property, but these are named using TitleCase convention (CSSPropertyFont), while the CSS features on Chrome Status are hyphenated (font-display). There is no feature in the HA dataset resembling "CSSFontDisplay". These are all of the Blink features (JS, HTML, or CSS) known to HA that include "font":
 
- CSSAtRuleFontFace
- kFontShapingNotDefGlyphObserved
- DocumentFonts
- FontFaceConstructor
- CSSAtRuleFontFeatureValues
- V8CSSFontFaceRule_Style_AttributeGetter
- FontSizeWebkitXxxLarge
- FontShapingNotDefGlyphObserved

It seems that HA and WPT aren't reporting the same list of CSS features used by Chrome Status. We should figure out how to extract these feature detections from Chrome using WPT and add them to the Chrome Status dashboard.

cc @pmeenan @igrigorik

**Comment by pmeenan** [comment]
There was originally a list of constants [here](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/frame/use_counter_helper.cc) but things have moved a lot and been refactored since then.

Would it be easier to report the feature number constants instead of maintaining a look-up-table on the agent side?  The numerical constant is what gets reported by the trace events.

**Comment by rviscomi** [comment]
Maybe we can reach out to someone who maintains those constants and get their input on the best way to keep these in sync. I like the idea of reporting feature names because they're readable, so it'd be great to have a resilient solution to keep them.

**Comment by rviscomi** [comment]
Correction: there _is_ a [CSSPropertyFontDisplay](https://datastudio.google.com/c/u/0/reporting/1M8kXOqPkwYNKjJhtag_nvDNJCpvmw_ri/page/tc5b?params=%7B%22df3%22:%22include%25EE%2580%25800%25EE%2580%2580IN%25EE%2580%2580CSSPropertyFontDisplay%22%7D) feature. And I believe this is the corresponding feature to the [font-display](https://chromestatus.com/metrics/css/timeline/popularity/516) dashboard, but there's a mismatch in the feature name (hyphen vs TitleCase).

The `_blinkFeatureFirstUsed.CSSFeatures` features were not being materialized into the dataset that powers the dashboard used by Chrome Status. I've fixed that but the naming mismatch is still preventing the data from appearing in the dashboard.

The materialization script/query was doing this: 

```
return Object.keys($._blinkFeatureFirstUsed.Features)
```

and I've since updated it to do this:

```
return Object.keys($._blinkFeatureFirstUsed.Features).concat(Object.keys($._blinkFeatureFirstUsed.CSSFeatures))
```

For example here's an updated list of all known features containing "font":

DocumentFonts
V8CSSFontFaceRule_Style_AttributeGetter
FontFaceConstructor
CSSAtRuleFontFace
CSSPropertyFontFamily
CSSPropertyFontVariantCaps
CSSPropertyFontVariantNumeric
FontShapingNotDefGlyphObserved
CSSPropertyWebkitFontSmoothing
CSSPropertyFontKerning
CSSPropertyFontFeatureSettings
CSSPropertyFontVariationSettings
CSSPropertyFontStretch
CSSAtRuleFontFeatureValues
CSSPropertyFontVariant
CSSPropertyFontSize
CSSPropertyFont
CSSPropertyFontWeight
CSSPropertyFontVariantEastAsian
CSSPropertyWebkitFontSizeDelta
CSSPropertyFontVariantLigatures
CSSPropertyAliasWebkitFontFeatureSettings
CSSPropertyFontStyle
CSSPropertyFontDisplay
FontSizeWebkitXxxLarge
kFontShapingNotDefGlyphObserved

**Comment by rviscomi** [comment]
We discussed this issue in the monthly meeting today.

From @pmeenan:

> Besides "Features", "CSSFeatures" and "AnimatedCSSFeatures" there will also be "FeaturesNumeric", "CSSFeaturesNumeric" and "AnimatedCSSFeaturesNumeric" at the same point in the tree.
>
> Do you want them to be just the feature number or do you want a prefix infront of each since the numbers will overlap?
> 
> i.e. Feature-33, CSS-33 and Animated-33 or just '33' in each of the separate trees? If you are going to flatten the numeric list then a prefix will be important, if not then just the number will be cleaner. 

Having second thoughts about having two similar branches of feature data, eg Features vs FeaturesNumeric. WDYT of a data structure that combines both types into a single object? For example, rather than `FeatureName: 101.01` as the key/value in the feature object:

```json
"_blinkFeatures": {
  "CSSFeatures": {
    "123": {"name": "FeatureName", "firstUsed": 101.01},
    "..."
  },
  "Features": {
    "..."
  }
}
```

Two changes: the key in the feature object would be the ID (not name) and the value would be an object containing name and firstUsed properties.

When I flatten the CSS/Animation/etc objects, I can use a schema like `[feature name, feature number, feature type, ...]` where "type" can be animation, css, etc, which I populate using the name of the feature's parent object.

**Comment by pmeenan** [comment]
I can make the change but it won't be backward compatible that way so it will break any existing queries.  I can make the update between HA crawls so it won't split a single crawl.

**Comment by rviscomi** [comment]
The materialized `blink_features` dataset could help bridge that incompatibility. I'll append the data using the new schema to keep it all internally consistent.

**Comment by pmeenan** [comment]
Crawl just finished so I just landed the change for next month.  Truncated sample:

```json
"_blinkFeatureFirstUsed": {
    "AnimatedCSSFeatures": [],
    "CSSFeatures": {
        "212": {
            "firstUsed": 1909.394,
            "name": "CSSPropertyAliasWebkitBoxShadow"
        },
        "130": {
            "firstUsed": 520.46299999999997,
            "name": "CSSPropertyTextIndent"
        },
        "90": {
            "firstUsed": 531.17499999999995,
            "name": "CSSPropertyMarginBottom"
        },
        "24": {
            "firstUsed": 519.58600000000001,
            "name": "CSSPropertyBackgroundColor"
        },
    }
    "Features": {
        "2712": {
            "firstUsed": 1295.3440000000001,
            "name": "WindowScreenX"
        },
        "217": {
            "firstUsed": 654.08699999999999,
            "name": "ElementPrefixedMatchesSelector"
        },
        "2710": {
            "firstUsed": 1278.7080000000001,
            "name": "WindowPageXOffset"
        },
        "2711": {
            "firstUsed": 750.44399999999996,
            "name": "WindowPageYOffset"
        }
    }
}
```

Yeah, I should probably round and truncate those numbers :D, but otherwise it is done.

**Comment by rviscomi** [comment]
I've updated the scheduled query that materializes the `blink_features.features` table to account for the old and new schemas:

```sql
#standardSQL
CREATE TEMP FUNCTION features(payload STRING)
RETURNS ARRAY<STRUCT<name STRING, type STRING>> LANGUAGE js AS
"""
  function getFeatureNames(featureMap, featureType) {
    try {
      return Object.entries(featureMap).map(([key, value]) => {
        if (value.name) {
          return {'name': value.name, 'type': featureType};
        }
        return {'name': key, 'type': featureType};
      });
    } catch (e) {
      return [{'name': e, 'type': 'error'}];
    }
  }
  
  $ = JSON.parse(payload);
  if (!$._blinkFeatureFirstUsed) return [];
  
  return getFeatureNames($._blinkFeatureFirstUsed.Features, 'default')
    .concat(getFeatureNames($._blinkFeatureFirstUsed.CSSFeatures, 'css'))
    .concat(getFeatureNames($._blinkFeatureFirstUsed.AnimatedCSSFeatures, 'animated-css'));
""";


SELECT
  REPLACE(SUBSTR(_TABLE_SUFFIX, 0, 10), '_', '') AS yyyymmdd,
  IF(ENDS_WITH(_TABLE_SUFFIX, 'desktop'), 'desktop', 'mobile') AS client,
  url,
  feature.name AS feature,
  feature.type
FROM
  `httparchive.pages.*`,
  UNNEST(features(payload)) AS feature
WHERE
  payload IS NOT NULL
```

The scheduled query that builds the `blink_features.usage` summary table used by Chrome Status was also updated to include the new `type` field (default, css, animation-css). I'll have to update the Chrome Status Dashboard to make use of the types.

The tables are scheduled to be regenerated on the first of the month, so I've set myself a reminder to check on them on Monday.

**Comment by rviscomi** [comment]
Verified that the data is updating correctly in the HTML/JS Chrome Status dashboard:

![image](https://user-images.githubusercontent.com/1120896/75724402-4d588a80-5cac-11ea-88f7-b14d2f46e733.png)

I actually had to change the scheduled queries to include the ID, but it's working now. The next step will be to pipe the ID and type fields into the dashboard. The final step is to edit the Chrome Status pages for CSS features to specify the feature ID and type='css' in the embedded dashboard URL rather than feature name. IDs may only be available in the February dataset though, so the timeseries won't have historical data unless we backfill previous months' IDs.

And I realized that feature IDs are not unique across types. For example, 84 corresponds to FormElement in the HTML/JS type and CSSPropertyLetterSpacing in the CSS type. So that's why both need to be passed into the dashboard.

**Comment by rviscomi** [comment]
I've modified the dashboard to be able to filter by feature name OR (type AND id). I'm not happy with the way the integration would work 😕

![image](https://user-images.githubusercontent.com/1120896/76467130-5093fa80-63bf-11ea-99ef-443677e1ecb6.png)

https://datastudio.google.com/c/embed/u/0/reporting/1M8kXOqPkwYNKjJhtag_nvDNJCpvmw_ri/page/tc5b?params=%7B%22df7%22:%22include%25EE%2580%25800%25EE%2580%2580IN%25EE%2580%2580css%22,%22df6%22:%22include%25EE%2580%25800%25EE%2580%2580IN%25EE%2580%258025%22%7D

For example, this is how we'd embed the CSSPropertyBackgroundImage dashboard. Inside that convoluted URI encoding scheme it sets type=css and id=25. There are a couple of issues with this approach:

- IDs are only available for features as of the 2020_02_01 dataset, so historical data is not visible. This isn't such a big deal because we can modify the materialized table to backfill IDs for known features. Still, not ideal.
- The feature name is not displayed in the filter control. This is a minor UI nit, but a bigger issue is that you can't use the filter to search for other features. Maybe this is ok because it may be weird to be on one feature page and look up a different feature in the dashboard.

![image](https://user-images.githubusercontent.com/1120896/76467273-a072c180-63bf-11ea-846d-bfcefc161960.png)

https://datastudio.google.com/c/embed/u/0/reporting/1M8kXOqPkwYNKjJhtag_nvDNJCpvmw_ri/page/tc5b?params=%7B%22df3%22:%22include%25EE%2580%25800%25EE%2580%2580IN%25EE%2580%2580CSSPropertyBackgroundImage%22%7D

On the other hand, this is how the dashboard would normally look if we set the feature name ("CSSPropertyBackgroundImage") directly in the embed URL. We don't have that specific feature name on the [Chrome Status page](https://www.chromestatus.com/metrics/css/timeline/popularity/25), only the ID (25) and property name ("background-image"). But I think we can account for ~80% of features if we do simply string manipulation on that property name to coerce it into the feature name recognized by the dashboard.

Here's a JS snippet to do the trick:

```js
// Capitalizes the first letter of a word.
function capitalize(word) {
  var letters = word.split('');
  letters[0] = letters[0].toUpperCase();
  return letters.join('');
}

// Converts 'background-image' to 'CSSPropertyBackgroundImage'.
function convertToFeatureName(property) {
  return 'CSSProperty' + property.split('-').map(capitalize).join('');
}
```

So if we convert the property to the feature name and inject that name into the embedded dashboard URI, I think it should work most of the time. I scraped all 642 property names from https://www.chromestatus.com/metrics/css/popularity, mapped them to their corresponding feature name, and tested which were in the dataset. Only 122 properties were unable to be matched with a feature in the dataset, and these are relatively obscure ones like "font-optical-sizing" and "webkit-region-fragment". I'm not sure if the mapping is wrong or if these features are just not used anywhere. Since this is an overall improvement, I'm not to concerned about these.

I don't think the WPT schema change was a total loss. It's still valuable to disambiguate feature IDs and names and provide a mechanism for users to find a feature by its ID.

**Comment by rviscomi** [comment]
With @jrobbins' help the fix is [live](https://chromestatus.com/metrics/css/timeline/popularity/516)! 


![image](https://user-images.githubusercontent.com/1120896/76577788-c28e4180-649c-11ea-9aa0-f2cb3d70cd26.png)
