### ISSUE TITLE
Add speed index to Loading Speed

### ISSUE THREAD

**Issue by paulirish** [HTTPArchive/httparchive.org#195]
A little curious that it's not included, especially since all the data is collected over in the bigquery repo.

Would it be trivial to add it to the UI?

**Comment by rviscomi** [comment]
Yeah there's a lot in BQ that we don't surface in the UI. It'd be pretty easy to add but the only question is if it's a valuable metric. In what ways would speed index be useful to you?

FWIW @igrigorik has expressed an interest in deprecating the existing Loading Speed report in favor of the field-based data in HA's [CrUX report](https://httparchive.org/reports/chrome-ux-report). As an extension of that, I've been considering revamping the UI to reflect the metrics included in the annual Almanac report.
