### ISSUE TITLE
summary_requests and summary_pages not updated for May 2020 in BigQuery

### ISSUE THREAD

**Issue by adnanyousef** [HTTPArchive/httparchive.org#204]
It seems like the BigQuery datasets `summary_requests` and `summary_pages` did not get updated for May 2020.

**Comment by rviscomi** [comment]
Progress on this issue: https://github.com/HTTPArchive/bigquery/commit/5a5f45ae9bbc6eb39bcd8c5df32119d1475ac2e2

**Comment by rviscomi** [comment]
Tables should be available now 👍

**Comment by adnanyousef** [comment]
Fantastic, thank you!
