### ISSUE TITLE
blink_features dataset stuck since May

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#208]
The `blink_features` dataset hasn't been updated since May. It's powered by two scheduled queries:

- the `features` table is generated by processing the entire `pages` dataset for Blink features
- the `usage` table is generated from a summary of the `features` table

The `features` scheduled query has been failing with this error:

> Resources exceeded during query execution: UDF out of memory.

The UDF mentioned in the error is a new function to help parse and map feature names, types, and IDs. I think it's failing because the query is processing all tables in the `pages` dataset redundantly each month and the total size is now exceeding 6 TB.

**Comment by rviscomi** [comment]
I've modified the `features` scheduled query to only process the `latest.pages_*` tables and append the results rather than querying everything and overwriting the table. This is good for efficiency but if there are any hiccups with a given month, it won't automatically get picked up by the next month's query.

To help identify when we miss the features for a month, I've added the dataset metadata to the [dashboard](https://datastudio.google.com/u/0/reporting/1jh_ScPlCIbSYTf2r2Y6EftqmX9SQy4Gn/page/SsPXB):

![image](https://user-images.githubusercontent.com/1120896/86945167-b8144980-c116-11ea-9574-20eb093a725d.png)

**Comment by bazzadp** [comment]
Reopening this as doesn't look to be solved as didn't get picked up for July or August.

**Comment by rviscomi** [comment]
Thanks, I'll investigate.

**Comment by rviscomi** [comment]
Updated to include the latest data

![image](https://user-images.githubusercontent.com/1120896/92770434-f1ac3f80-f367-11ea-87aa-ab2142f046ce.png)

I tweaked the scheduled query timings to avoid race conditions, but ideally we generate this stuff at the end of the monthly crawl pipeline rather than asynchronously using scheduled queries. I'll close this out and make a new bug for that.
