### ISSUE TITLE
Significant changes in Lighthouse perf results in August 2020 run

### ISSUE THREAD

**Issue by brendankenny** [HTTPArchive/httparchive.org#217]
Looking at Lighthouse scores in the August vs July 2020 runs, 70% of sites got a boost in their Lighthouse perf score, 50% adding 3 or more points, 25% adding 10 points, and 10% of sites adding almost 20 points to their perf scores.

Significant improvements in TBT appear to be the proximate cause (reduced by ~50% for the most CPU heavy sites), but all the CPU numbers seem to have been cut significantly (25-30% reduction in total main-thread task times across all sites).

Is there a known reason for this? There was nothing in the new Lighthouse 6.2 release in August that should have caused this, and we haven't seen similar changes on other Lighthouse clients.

We think maybe it was the removal of cgroups throttling in favor of devtools throttling mentioned in https://github.com/WPO-Foundation/wptagent/pull/366#issuecomment-662535573, but wanted to be sure and see if others have noticed the effect.

cc @rviscomi @pmeenan @paulirish @patrickhulce

**Comment by pmeenan** [comment]
WPT changed the mobile CPU throttling to use Chrome's built-in throttling (which matches what lighthouse uses natively) instead of the OS-level cgroups.  The cgroups seemed to have more overhead than expected when run in the cloud VM's, even when enabled but set to not throttle.

**Comment by patrickhulce** [comment]
Thanks @pmeenan! I guess we're somewhat incredulous that the DevTools throttling is actually being applied in the Lighthouse case given these numbers.

Taking a random page out as an example from the latest dataset...

http://www.pisigmaalpha.org/

WebPageTest result reported ~30s of total CPU execution time, longest task of 2.4s, and a page test that lasted 45s.

Lighthouse result reported ~4s of main-thread CPU execution time, longest task of 600ms, and a page test that lasted 23s.

The longest task in particular suggests to me that it's possible the DevTools throttling isn't being applied in HTTPArchive for the Lighthouse run. It's also possible I'm interpreting the WPT JSON results incorrectly, but either way would really appreciate a second look
 :)

See [wpt-v-lh.zip](https://github.com/HTTPArchive/httparchive.org/files/5152496/wpt-v-lh.zip) or query HTTPArchive for the results.

**Comment by rviscomi** [comment]
We were planning to use the August dataset's Lighthouse results in the 2020 Web Almanac. Given that the throttling change seems to be creating many more false negatives in the audits we should either try to get this fixed for the September crawl (starting tomorrow) or on the Almanac side we'll have to use the July dataset for any metrics that depend on throttled audits.

**Comment by pmeenan** [comment]
I'll look closer. [here](https://www.webpagetest.org/result/200831_Y1_b0ab093e5fdf4a9250044ab6bc1258b9/1/details/#waterfall_view_step1) is a WPT test for that page at 3GFast along with the accompanying LH report.

Lighthouse has the main-r.min.js total script execution time at 2199ms and WPT has it at ~2400ms (2298 function call time).  

In the debug log for the Lighthouse run I'm seeing
```
21:07:20.598 - DevTools CPU Throttle target: 1.445x
```

Which is only output [when the CPU throttling is being applied](https://github.com/WPO-Foundation/wptagent/blob/master/internal/devtools_browser.py#L135).

That said, I also tried it out on the Windows thinkpads (faster machines) and the CPU time in lighthouse for that script was around half what it was in WPT (but still more than when there was no throttling).

It's possible that something is wiping out the devtools throttling after lighthouse takes over the existing connection but then I'd also expect it to impact the mobile device emulation (form factor, etc) which are also set up by WPT.

There's also [this issue](https://github.com/WPO-Foundation/wptagent/issues/372) where Chrome's CPU throttling seems to be flaky based on the site-per-process sandboxing.

**Comment by pmeenan** [comment]
Looks like [Lighthouse explicitly overwrites](https://github.com/GoogleChrome/lighthouse/blob/7e2ce68df6caaede7e0f5c07007e169a0b651015/lighthouse-core/gather/driver.js#L1382) the devtools-based throttling if it isn't applying throttling.

Unfortunately it looks like the CPU and Network throttling are both linked and I can't pass Lighthouse a CPU throttling (or tell it not to erase my settings) without also passing it a network throttling config (and the devtools network throttling is very much unwanted).

Exploring options now. Best chance would be if there are values for Chrome's networking throttling that when passed have the same effect as turning it off (like 0 for all of the settings).

**Comment by pmeenan** [comment]
oooh, passing "devtools" instead of "provided" as the throttling method looks like it might do what I want and reset network throttling and not touch CPU throttling.

**Comment by patrickhulce** [comment]
Ahhhh great find @pmeenan! Yeah this is definitely it then. We actually had this mistaken in our docs until recently you might've copied it from us 😬 

We probably want...

```bash
# Run Lighthouse with its own network throttling disabled (while leaving CPU throttling)
lighthouse --throttling-method=devtools \
  --throttling.requestLatencyMs=0 \
  --throttling.downloadThroughputKbps=0 \
  --throttling.uploadThroughputKbps=0 \
  ... \
  https://example.com

**Comment by patrickhulce** [comment]
Re: `DevTools CPU Throttle target: 1.445x` that sounds surprisingly low to me based on some recent LH [investigations](https://github.com/GoogleChrome/lighthouse/blob/aac0b68458e17a885d5236c1166f5cd5b82250db/docs/throttling.md#calibrating-multipliers). Is this from a `n2-standard-2` or similar cloud VM down to a Moto G4?

**Comment by patrickhulce** [comment]
Wait hang on @pmeenan that branch you highlighted for disabling CPU throttling only happens when `throttlingMethod` *is* `devtools` I'm not sure that explains what we're seeing 🤔 

https://github.com/GoogleChrome/lighthouse/blob/7e2ce68df6caaede7e0f5c07007e169a0b651015/lighthouse-core/gather/driver.js#L1378

**Comment by pmeenan** [comment]
Oh, doh - thanks.  I need to read the !== closer.

I'm not certain yet that the CPU throttling isn't working. I'll see if I can put together a stronger test case that will make it crystal clear.

**Comment by pmeenan** [comment]
I verified that with "provided" the CPU throttling is definitely not working.  I set up a JSBin with a [busy loop](https://jsbin.com/joranafizi/edit?html,output) and it runs way too fast in Lighthouse in local testing.

If I explicitly pass it for devtools then the CPU throttling is applied correctly and both WPT and Lighthouse take the same amount of time.

**Comment by pmeenan** [comment]
Just pushed a fix: https://github.com/WPO-Foundation/wptagent/commit/908914f6d02138f94531d99a41c15f1c0fd4b615

The agents will pick it up before the crawl starts tonight.  I'm going to do some more testing just to make sure there are no side-effects on the network side of things.

**Comment by pmeenan** [comment]
[Here](https://www.webpagetest.org/result/200831_GX_6ac68cf59c7183f00c86addff0c2e787/) is a test with the fix and the jsbin running on the fast thinkpads, emulating a Moto G1.  Both Ligthouse and WPT take around 20 seconds to load it. Without throttling it takes around [7 seconds](https://www.webpagetest.org/result/200831_1Q_19f29eef04d834eb6a3723595b7bd3ac/).

At this point I'm pretty confident that it was broken in the August crawl and is fixed for the September crawl.

**Comment by patrickhulce** [comment]
Huzzah! Thanks so much for getting to the bottom of this @pmeenan we really appreciate it! Perhaps there is something in the connection hand off process that causes the throttling set by WPT to become disabled then even if LH isn't explicitly overriding it. Either way thanks a million 🙏

**Comment by patrickhulce** [comment]
Before it's fully closed out... 

> Re: DevTools CPU Throttle target: 1.445x that sounds surprisingly low to me based on some recent LH investigations. Is this from a n2-standard-2 or similar cloud VM down to a Moto G4?

Do you happen to have links to how the throttling multiplier is decided or even just pointers into where I should be looking into agent source? :)

We recently spent a decent chunk of time trying to calibrate JS-execution time across devices in Lighthouse and I'd love to add the findings you've had over the years to this too.

**Comment by pmeenan** [comment]
That was from the Dulles VMs. On my desktop it was closer to 5.

The agent runs a sha1 benchmark at startup (in python) and compares it to a
reference time to adjust the multiplier from the reference measurements.

The reference measurements were measured by pulling the js times from a few
heavy sites on real devices and then adjusting the multiplier on a
reference VM until the times were similar.

**Comment by brendankenny** [comment]
Thanks all!

**Comment by rviscomi** [comment]
Thanks for spotting this @brendankenny and @pmeenan for the fix!

**Comment by paulirish** [comment]
FWIW @brendankenny did an analysis a while ago comparing the cgroups and devtools throttling against Lighthouse w/ lantern (simulated) throttling.     

https://github.com/GoogleChromeLabs/lh-metrics-analysis/blob/gh-pages/reports/manual/2020-10-http-archive-throttling-vs-cli/report.md


There isn't a direct comparison between the two WPT+HA populations, but you can kinda see it between multiple plots. :)

**Comment by tunetheweb** [comment]
Think we can close this now.
