### ISSUE TITLE
Reimplement summary tables from raw HAR data

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#23]
The legacy website uses intermediate crawl data from MySQL tables to generate CSVs containing summary data about pages and requests. As part of the beta migration, we would like to deprecate this preprocessing step and depend directly on the raw HAR data.

In BigQuery, this data is represented in the `runs` dataset, which has recently been split into `summary_pages` and `summary_requests`. These datasets will continue to exist, but will be generated in a BigQuery post-processing step instead, using the HAR tables as input.

A secondary goal of this process is to modernize the summary data. For example, the `videoRequests` field may not count modern video formats like WebM.

- [ ] Write new queries to replicate summary data
- [ ] Hook queries into post-processing pipeline
- [ ] Unplug CSV -> BigQuery pipeline
- [ ] Remove pre-processing logic

**Comment by rviscomi** [comment]
`requests.2019_03_01_desktop` would be a good place to start because we lost a lot of data in the `summary_requests.2019_03_01_desktop` table.

**Comment by Themanwithoutaplan** [comment]
I might take a look at this. Note, the requests table is required for some of the statistical analysis for each run but this is essentially a one-off task that can be done differently. CSVs can be useful so HAR to CSV would be useful. I already have the code for this in Python in my fork of httparchive.
