### ISSUE TITLE
BigQuery missing for the month of November (2020_11_01)

### ISSUE THREAD

**Issue by infosec-au** [HTTPArchive/httparchive.org#232]
Hi,

I'm unable to find the tables in BigQuery which have data for the month of November (2020_11_01).

I generate new wordlists (wordlists.assetnote.io) each time data is released on BigQuery for the HTTPArchive. I noticed from previous table uploads, a new table is uploaded roughly on the 24th of each month.

This hasn't seem to have happened for November. Is it still planned to release the dataset for November? I just wanted to raise this issue incase it was an oversight or problem during data upload that may not have been realised yet.

Thanks again for all your hard work on this project.

**Comment by rviscomi** [comment]
Hi, thanks for flagging this. We're currently unable to use our existing dataflow pipeline to transfer data into BigQuery as its SDK version is no longer supported. We need to find the time to invest in upgrading the pipeline to a supported version. [Source code here](https://github.com/HTTPArchive/bigquery/blob/master/dataflow/java/src/main/java/com/httparchive/dataflow/BigQueryImport.java) if you or anyone else is interested to help.

**Comment by infosec-au** [comment]
I can't help with writing the fix due to time constraints myself, however would be happy to donate to the project or put a bounty on the fix if that helps.

If this would help can you please let me know? We are heavily reliant on the BigQuery data being uploaded and would like to contribute somehow to this fix. I couldn't find a donate link for the project.

**Comment by rviscomi** [comment]
That's a very kind offer, thank you @infosec-au. We're not currently set up to do bug bounties (maybe in 2021?) but if you'd still like to donate to the project you can do so at archive.org/donate and be sure to include a comment that it's for HTTP Archive.

Out of curiosity, could you tell me more about your use case and how you use the BigQuery dataset?

Hopefully we can get the pipeline issue resolved soon.

**Comment by infosec-au** [comment]
Sure. I'll donate via Archive.org.

I generate wordlists that are used by security professionals. These wordlists are available at https://wordlists.assetnote.io.

We have built Commonspeak2 which relies on the HTTPArchive dataset: https://github.com/assetnote/commonspeak2/

This process gets automatically executed through GitHub actions found here: https://github.com/assetnote/wordlists/blob/master/.github/workflows/wordlists.yml

Our wordlists are quite useful for security testing, and we are trying to create evolving wordlists that evolve as the web, and ultimately as the HTTPArchive dataset updates.
