### ISSUE TITLE
Native Image Lazy Loading metric incorrect

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/httparchive.org#233]
As raised on Slack by @rockeynebhwani , I think the metric introduced in #216 is incorrect:

Current SQL:

```sql
#standardSQL
SELECT
  SUBSTR(_TABLE_SUFFIX, 0, 10) AS date,
  UNIX_DATE(CAST(REPLACE(SUBSTR(_TABLE_SUFFIX, 0, 10), '_', '-') AS DATE)) * 1000 * 60 * 60 * 24 AS timestamp,
  IF(ENDS_WITH(_TABLE_SUFFIX, 'desktop'), 'desktop', 'mobile') AS client,
  ROUND(COUNT(DISTINCT IF(LOWER(attr) = '"lazy"', url, NULL)) * 100 / COUNT(0), 2) AS percent
FROM
  `httparchive.pages.*`,
  UNNEST(JSON_EXTRACT_ARRAY(JSON_EXTRACT_SCALAR(payload, "$['_img-loading-attr']"), '$')) AS attr
GROUP BY
  date,
  timestamp,
  client
ORDER BY
  date DESC,
  client
```

I think this is incorrect and is counting images instead of pages, but then total is also incorrect. I think this should be:

```sql
#standardSQL
SELECT
  SUBSTR(_TABLE_SUFFIX, 0, 10) AS date,
  UNIX_DATE(CAST(REPLACE(SUBSTR(_TABLE_SUFFIX, 0, 10), '_', '-') AS DATE)) * 1000 * 60 * 60 * 24 AS timestamp,
  IF(ENDS_WITH(_TABLE_SUFFIX, 'desktop'), 'desktop', 'mobile') AS client,
  ROUND(COUNT(DISTINCT url) * 100 / total, 2) AS percent
FROM
  `httparchive.pages.*`,
  UNNEST(JSON_EXTRACT_ARRAY(JSON_EXTRACT_SCALAR(payload, "$['_img-loading-attr']"), '$')) AS attr
JOIN
  (SELECT _TABLE_SUFFIX, COUNT(DISTINCT url) AS total FROM `httparchive.pages.*` where SUBSTR(_TABLE_SUFFIX, 0, 10) = '2020_08_01' GROUP BY _TABLE_SUFFIX)
USING
  (_TABLE_SUFFIX)
WHERE
  LOWER(attr) = '"lazy"' AND
  SUBSTR(_TABLE_SUFFIX, 0, 10) = '2020_08_01'
GROUP BY
  date,
  timestamp,
  client,
  total
ORDER BY
  date DESC,
  client
```

Current sql (including working columns):

date | timestamp | client | count_attr | count_0 | percent
-- | -- | -- | -- | -- | --
2020_08_01 | 1.59624E+12 | desktop | 20,660,900 | 4,089,397 | 5.05
2020_08_01 | 1.59624E+12 | mobile | 24,592,000 | 4,960,657 | 4.96

As you can see the `count_attr` column is way t0o high (so counting images not pages) and the `count_0` column is also too low (only counting pages with images?).

New sql (including working columns):

date | timestamp | client | count_distinct_url | count_0 | total | percent
-- | -- | -- | -- | -- | -- | --
2020_08_01 | 1.59624E+12 | desktop | 206,609 | 3,958,652 | 5,593,642 | 3.69
2020_08_01 | 1.59624E+12 | mobile | 245,920 | 4,851,598 | 6,347,640 | 3.87

Alternatively if you only want to look at pages with images, you'll get slightly higher percentages (since pages using it is same, but total is less):

date | timestamp | client | count_distinct_url | count_0 | total | percent
-- | -- | -- | -- | -- | -- | --
2020_08_01 | 1.59624E+12 | desktop | 206,609 | 3,958,652 | 5,587,230 | 3.7
2020_08_01 | 1.59624E+12 | mobile | 245,920 | 4,851,598 | 6,339,352 | 3.88

by using the following SQL:

```sql
#standardSQL
SELECT
  SUBSTR(_TABLE_SUFFIX, 0, 10) AS date,
  UNIX_DATE(CAST(REPLACE(SUBSTR(_TABLE_SUFFIX, 0, 10), '_', '-') AS DATE)) * 1000 * 60 * 60 * 24 AS timestamp,
  IF(ENDS_WITH(_TABLE_SUFFIX, 'desktop'), 'desktop', 'mobile') AS client,
  COUNT(DISTINCT url) as count_distinct_url,
  COUNT(0) as count_0,
  total,
  ROUND(COUNT(DISTINCT url) * 100 / total, 2) AS percent
FROM
  `httparchive.pages.*`,
  UNNEST(JSON_EXTRACT_ARRAY(JSON_EXTRACT_SCALAR(payload, "$['_img-loading-attr']"), '$')) AS attr
JOIN
  (SELECT _TABLE_SUFFIX, COUNT(DISTINCT url) AS total FROM `httparchive.summary_pages.*` where SUBSTR(_TABLE_SUFFIX, 0, 10) = '2020_08_01' AND bytesImg > 0 GROUP BY _TABLE_SUFFIX)
USING
  (_TABLE_SUFFIX)
WHERE
  LOWER(attr) = '"lazy"' AND
  SUBSTR(_TABLE_SUFFIX, 0, 10) = '2020_08_01'
GROUP BY
  date,
  timestamp,
  client,
  total
ORDER BY
  date DESC,
  client
```

**Comment by rviscomi** [comment]
Great catch, thanks @bazzadp and @rockeynebhwani!

**Comment by rviscomi** [comment]
The stat is updated in the [Images report](https://httparchive.org/reports/state-of-images?start=2020_07_01&end=latest&view=grid#imgLazy):

![image](https://user-images.githubusercontent.com/1120896/103378686-2841cd80-4ab1-11eb-9929-1d2a6727e53d.png)

And the [WordPress lens](https://httparchive.org/reports/state-of-images?lens=wordpress&start=2020_07_01&end=latest&view=grid#imgLazy):

![image](https://user-images.githubusercontent.com/1120896/103379001-2e847980-4ab2-11eb-97d8-a88839352993.png)

I don't remember if the adoption rate was growing this much with the incorrect version but this is definitely impressive growth. It seems to be almost entirely driven by WordPress! cc @felixarntz
