### ISSUE TITLE
Jan 2021 stats dump is empty

### ISSUE THREAD

**Issue by Themanwithoutaplan** [HTTPArchive/httparchive.org#235]
Something obviously went wrong here. Is this another file that's now on the Google architecture?

Verbindungsaufbau zu legacy.httparchive.org (legacy.httparchive.org)|208.70.31.93|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 20 [application/octet-stream]

**Comment by bazzadp** [comment]
Could you give more info of what's up @Themanwithoutaplan ?

Did you mean Jan 2021 rather than 2020? That's still being processed and should be available soon.

**Comment by Themanwithoutaplan** [comment]
Yes, 2021, sorry.

**Comment by bazzadp** [comment]
So Desktop data is mostly there in BiqQuery now but Mobile is still being processed. Should be there in a few days.

Can you explain exactly what you are looking for (BigQuery data? Something else?) and when you normally expect this to be ther?

**Comment by Themanwithoutaplan** [comment]
Thanks for the update. I'm used to the datasets being update sequentially: previous dataset, desktop, mobile. But I've never had an empty file yet.

I've been running comparative analyses on the data for years. The aggregated data is required to identify the browser. For my analyses it makes **much** more sense to use a relational database than big query, which is why I rely on the datasets.

**Comment by bazzadp** [comment]
Can you please describe where you get the dataset from? Rick’s away at the mo so a few of us trying to cover so not totally familiar with all this so more details you can give us the better.

**Comment by pmeenan** [comment]
Which dump?  Looks like the mobile one hasn't been created yet as best as I can tell.

**Comment by pmeenan** [comment]
It's possible there's a problem with the mobile csv (looking now) but all of the other dumps look to be on Google storage:

```bash
$ gsutil ls -l gs://httparchive/downloads/*2021*
 941433047  2021-01-17T11:01:51Z  gs://httparchive/downloads/httparchive_Jan_1_2021_pages.csv.gz
 850306683  2021-01-17T11:02:46Z  gs://httparchive/downloads/httparchive_Jan_1_2021_pages.gz
87304944394  2021-01-18T11:37:29Z  gs://httparchive/downloads/httparchive_Jan_1_2021_requests.csv.gz
86202400261  2021-01-17T21:26:02Z  gs://httparchive/downloads/httparchive_Jan_1_2021_requests.gz
1125151289  2021-01-19T13:01:54Z  gs://httparchive/downloads/httparchive_mobile_Jan_1_2021_pages.csv.gz
1018627337  2021-01-19T13:02:53Z  gs://httparchive/downloads/httparchive_mobile_Jan_1_2021_pages.gz
         0  2021-01-19T13:02:55Z  gs://httparchive/downloads/httparchive_mobile_Jan_1_2021_requests.csv.gz
2306569335  2021-01-19T13:05:10Z  gs://httparchive/downloads/httparchive_mobile_Jan_1_2021_requests.gz
TOTAL: 8 objects, 179749432346 bytes (167.4 GiB)
```

**Comment by pmeenan** [comment]
The mobile requests looks suspiciously small - definitely a problem there

**Comment by Themanwithoutaplan** [comment]
httparchive_stats.gz from legacy.httparchive.org. This doesn't appear to be on Google.
This normally updates for each dataset shortly after pages.csv becomes available. But obviously a bit different this month.

**Comment by pmeenan** [comment]
Looks like the mobile requests table may be corrupt somehow and is crashing mysql which caused the dump to fail (and probably downstream work after it)

**Comment by Themanwithoutaplan** [comment]
So that's what's presumably preventing the creation of the stats? I can work around this for most of my work.

**Comment by tunetheweb** [comment]
Closing as cleaning up and unable to regenerate.
