### ISSUE TITLE
High number of sharded content sites

### ISSUE THREAD

**Issue by Themanwithoutaplan** [HTTPArchive/httparchive.org#236]
I was looking at the distribution of websites across SpeedIndex and came across a surprising number of essentially sharded websites, such as *.photobucket.com. I know that since the delegation of websites to CrUX there is no intervention in the website list but I wondered if there might no be sufficient similar websites to have an effect in some of the metrics. If there is an effect I'm not sure how to mitigate it except perhaps by limiting the number of subdomains.

**Comment by rviscomi** [comment]
I understand the concern about user-generated subdomains skewing results. I think as long as our major public reports (like Web Almanac) clarify in the methodology how the URLs are sourced, the effect is tolerable.

Appreciate the issue but I think we can close it as WAI.
