### ISSUE TITLE
Move from master to main inline with Web Almanac

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/httparchive.org#242]
@rviscomi / @pmeenan do you see any issues with this? I think the legacy.htttparchive.org project is still referenced by WebPageTest for custom metrics but don't think this project is so don't think there are any dependencies. But let me know if that is not the case.

**Comment by pmeenan** [comment]
No dependencies, should be safe to switch (famous last words).

**Comment by rviscomi** [comment]
SGTM

**Comment by bazzadp** [comment]
`master` has been renamed to `main`

Please apply the following changes to update any local copy

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```
