### ISSUE TITLE
_cpu.v8.compile missing

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#27]
`_cpu.v8.compile` appears 0 times in any of the four crawls' HAR payloads in February. It made 45562739 appearances the previous month. @pmeenan is this intentional/expected? 

This data is currently used in the [compileJs metric](https://beta.httparchive.org/reports/state-of-javascript?start=2018_01_15#compileJs), so recent crawls have [broken](https://beta.httparchive.org/reports/state-of-javascript?start=2018_02_01#compileJs) charts ([fix pending](https://github.com/HTTPArchive/beta.httparchive.org/pull/26/commits/85e9f667ef614ea2e2d72c9886cb1067d066953c)).

![image](https://user-images.githubusercontent.com/1120896/37508605-2fbce8c6-28ca-11e8-88a1-b8372eeef7d3.png)

**Comment by pmeenan** [comment]
Not a change on the WPT side but it may reflect underlying v8 changes.  I just tested [CNN with Chrome](https://www.webpagetest.org/result/180317_KR_1bd8146115bd0d8376fcfbb08f3d912e/1/details/#waterfall_view_step1) 65 and see the following:

```
"_cpu.Layout": 1309,
"_cpu.XHRLoad": 28,
"_cpu.UpdateLayerTree": 1949,
"_cpu.HitTest": 417,
"_cpu.Paint": 163,
"_cpu.v8.compile": 695,
"_cpu.TimerFire": 571,
"_cpu.XHRReadyStateChange": 16,
"_cpu.ParseAuthorStyleSheet": 116,
"_cpu.UpdateLayoutTree": 1491,
"_cpu.CommitLoad": 1,
"_cpu.EventDispatch": 155,
"_cpu.ScriptWrappableVisitor::performLazyCleanup": 0,
"_cpu.ResourceChangePriority": 0,
"_cpu.MinorGC": 205,
"_cpu.PlatformResourceSendRequest": 26,
"_cpu.MajorGC": 57,
"_cpu.BlinkGCMarking": 132,
"_cpu.ResourceSendRequest": 0,
"_cpu.ThreadState::completeSweep": 35,
"_cpu.EvaluateScript": 1674,
"_cpu.FireIdleCallback": 13,
"_cpu.FireAnimationFrame": 344,
"_cpu.FunctionCall": 6310,
"_cpu.ThreadState::performIdleLazySweep": 3,
"_cpu.ParseHTML": 188,
"_cpu.Idle": 14557,
```

It looks like compile was there for this case at least.  I'll poke around to make sure it is coming through on the HTTP Archive instance as well.

**Comment by rviscomi** [comment]
This is obsolete
