### ISSUE TITLE
CrUX reports not updated since Jan 1st 2020

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/httparchive.org#306]
https://httparchive.org/reports/chrome-ux-report

Log files:

```
Generating cruxFastDcl timeseries
Error in query string: Error processing job 'httparchive:bqjob_r2b6bc8914f072fa8_000001794498c939_1': No matching signature for function REGEXP_REPLACE for argument types: INT64, STRING, STRING. Supported signatures: REGEXP_REPLACE(
STRING, STRING, STRING); REGEXP_REPLACE(BYTES, BYTES, BYTES) at [3:3]
Generating cruxFastFcp timeseries
Error in query string: Error processing job 'httparchive:bqjob_r4692398fae55387b_000001794498d17c_1': No matching signature for function REGEXP_REPLACE for argument types: INT64, STRING, STRING. Supported signatures: REGEXP_REPLACE(
STRING, STRING, STRING); REGEXP_REPLACE(BYTES, BYTES, BYTES) at [3:3]
Generating cruxFastFid timeseries
Error in query string: Error processing job 'httparchive:bqjob_r296744bf427475d3_000001794498d901_1': No matching signature for operator >= for argument types: INT64, STRING. Supported signature: ANY >= ANY at [10:3]
Generating cruxFastFp timeseries
Error in query string: Error processing job 'httparchive:bqjob_rb7f24b391d9d91_000001794498e0d7_1': No matching signature for function REGEXP_REPLACE for argument types: INT64, STRING, STRING. Supported signatures: REGEXP_REPLACE(ST
RING, STRING, STRING); REGEXP_REPLACE(BYTES, BYTES, BYTES) at [3:3]
Generating cruxFastOl timeseries
Error in query string: Error processing job 'httparchive:bqjob_r16fe42e03c18ba99_000001794498e905_1': No matching signature for function REGEXP_REPLACE for argument types: INT64, STRING, STRING. Supported signatures: REGEXP_REPLACE(
STRING, STRING, STRING); REGEXP_REPLACE(BYTES, BYTES, BYTES) at [3:3]
Generating cruxSlowFcp timeseries
Error in query string: Error processing job 'httparchive:bqjob_r7d1938708f4fb81b_000001794498f0b4_1': No matching signature for function REGEXP_REPLACE for argument types: INT64, STRING, STRING. Supported signatures: REGEXP_REPLACE(
STRING, STRING, STRING); REGEXP_REPLACE(BYTES, BYTES, BYTES) at [3:3]
Generating cruxSlowFid timeseries
Error in query string: Error processing job 'httparchive:bqjob_r278ce531c9567861_000001794498f90c_1': No matching signature for operator >= for argument types: INT64, STRING. Supported signature: ANY >= ANY at [10:3]
Generating dcl timeseries
```

These look to me like we need to replace these:

```
  REGEXP_REPLACE(yyyymm, '(\\d{4})(\\d{2})', '\\1_\\2_01') AS date,
  UNIX_DATE(CAST(REGEXP_REPLACE(yyyymm, '(\\d{4})(\\d{2})', '\\1-\\2-01') AS DATE)) * 1000 * 60 * 60 * 24 AS timestamp,
```

with these:

```
  REGEXP_REPLACE(CAST(yyyymm AS STRING), '(\\d{4})(\\d{2})', '\\1_\\2_01') AS date,
  UNIX_DATE(CAST(REGEXP_REPLACE(CAST(yyyymm AS STRING), '(\\d{4})(\\d{2})', '\\1-\\2-01') AS DATE)) * 1000 * 60 * 60 * 24 AS timestamp,
```

@rviscomi do you know if these changed from strings to ints? Cause this was last changed [on April 2019](https://github.com/HTTPArchive/bigquery/pull/72/files) but then it worked for rest of 2019 and then stop after Jan 2020?

I also noticed some of the histogram jobs are failing:

```
enerating cruxDcl histogram
BigQuery error in query operation: Error processing job 'httparchive:bqjob_r214ea6c060a289eb_0000017945c69c31_1': Not found: Table chrome-ux-report:all.202104 was not found in location US
Generating cruxFcp histogram
BigQuery error in query operation: Error processing job 'httparchive:bqjob_r8b44e5b7a5d5889_0000017945c6a3e9_1': Not found: Table chrome-ux-report:all.202104 was not found in location US
Generating cruxFid histogram
BigQuery error in query operation: Error processing job 'httparchive:bqjob_r2779c4ec5ebc2ec3_0000017945c6ac8a_1': Not found: Table chrome-ux-report:all.202104 was not found in location US
Generating cruxFp histogram
BigQuery error in query operation: Error processing job 'httparchive:bqjob_r5f420d88db16b8b_0000017945c6b43d_1': Not found: Table chrome-ux-report:all.202104 was not found in location US
Generating cruxOl histogram
BigQuery error in query operation: Error processing job 'httparchive:bqjob_r7ee13d46bfa92415_0000017945c6bc13_1': Not found: Table chrome-ux-report:all.202104 was not found in location US
```

This looks to me more a timing issue. The April data only came out yesterday. So how does this work if it's always a month behind? Or has this been failing forever? Looks like to me the data is missing for a while - except when we rerun for a previous month (like we did for 202103 - [example report](https://storage.googleapis.com/httparchive/reports/2021_03_01/cruxDcl.json)).

Also where are these histograms surfaced out of interest? Don't see them on the site - are they for the legacy site?

**Comment by rviscomi** [comment]
You're right that this is a timing issue. I think the intention was to hook these CrUX-based reports into a PubSub service so that they can get generated after the monthly CrUX dataset is released, but never got to it. I think it's worth rethinking the CrUX report into more of a Core Web Vitals report while we're making changes.

Histograms are unfortunately kind of a hidden/pro feature. There isn't an obvious UI to enable them. To enable it, the start/end dates need to be equal, or the end date unset, for example: https://httparchive.org/reports/state-of-the-web?start=latest

**Comment by bazzadp** [comment]
OK let's split these up into a few different parts:
- [ ] - Fix time series with above suggested fix - https://github.com/HTTPArchive/bigquery/pull/95
- [ ] - Fix histograms short term (maybe a cron-ed report?)
- [ ] - Fix histograms long term with PubSub
- [ ] - Rewrite CrUX report as Core Web Vitals report (maybe this should be a separate issue?)

**Comment by bazzadp** [comment]
Closing this after work completed in #320 , #324 , #327 

Not implemented PubSub for CrUX but have a cron report in meantime and also the report checker's been updated to check for previous month.

Not rewritten CrUX report for CWV but have added LCP and CLS in existing format and reordered to put CWV at the top.
