### ISSUE TITLE
When might be a good time to disable TLS 1.0 and 1.1 on httparchive.org ?

### ISSUE THREAD

**Issue by cqueern** [HTTPArchive/httparchive.org#315]
Should impact few, if any users. Level of effort should be pretty low.

**Comment by rviscomi** [comment]
We use a Google-managed certificate for our site hosted on App Engine. Relevant docs on TLS version configs: https://cloud.google.com/load-balancing/docs/ssl-policies-concepts

**Comment by bazzadp** [comment]
Yeah was just reading this. It’s easily possible to tweak this if we want to.

Here comes a big bug bear with this (I have this issue at work too!). CDNs in general are **shockingly bad** at exposing what versions of TLS and ciphers your traffic uses to help you make decisions like these. So while I agree with @cqueern it’s probably low it would still be a guess based on Google Analytics data. Though I’m digging through Google Cloud to see if it’s there.

I’m torn. On one side I like to follow best practices on sites like HTTPArchive.org and the Web Almanac site. On the other hand there really is no sensitive data here and modern browsers won’t use TLSv1.0 or below so the risk is minuscule and we may cut off some users. Users who are likely already cut off from large parts of the Internet admittedly, but still - we like to be inclusive.

I’d probably vote to only support TLSv1.2 or above if you’re comfortable with this @rviscomi ?

**Comment by cqueern** [comment]
Maybe we disable TLS 1.0 and 1.1 for a few weeks as an experiment and if there are few or no objections, we leave them disabed.

**Comment by rviscomi** [comment]
SGTM

**Comment by bazzadp** [comment]
Updated it to TLSv1.2 using the Modern cipher selection: https://cloud.google.com/load-balancing/docs/ssl-policies-concepts

Old SSL Labs score:

![image](https://user-images.githubusercontent.com/10931297/118725525-f646c300-b827-11eb-8b64-3f447c65b45c.png)

Not sure how long it takes to take effect but currently still showing TLSv1.0 support so will check again later using this link: https://www.ssllabs.com/ssltest/analyze.html?d=httparchive.org&hideResults=on&clearCache=on

**Comment by bazzadp** [comment]
Set here btw: https://console.cloud.google.com/net-services/loadbalancing/edit/http/httparchive-load-balancer?project=httparchive

Then go to Frontend Configuration -> HTTP... 443 and flip Policy between `GCP Default` (our old policy) and `modern-tls12-min` (a new policy I created).

If it breaks while I'm asleep then just flip it back.

**Comment by rviscomi** [comment]
I think the load balancer only controls the frontend for our GCS bucket (cdn.httparchive.org) as opposed to all traffic through httparchive.org.

**Comment by bazzadp** [comment]
That might explain why it's still not updating! Though cdn.httparchive.org gets a nice green A now: https://www.ssllabs.com/ssltest/analyze.html?d=cdn.httparchive.org&hideResults=on

Hmmm... can't find a setting other than that for the actual site...

**Comment by rviscomi** [comment]
Noob question, is there any incompatibility risk of the `cdn` origin using one policy and the main domain using another?

**Comment by bazzadp** [comment]
> Noob question, is there any incompatibility risk of the `cdn` origin using one policy and the main domain using another?

Well it's possible that they load httparchive.org from a really old browser, and then fail to load some of the resources needed by the report page and so the report doesn't load. That's the worst I can think off.

However, if we can't change the main site (and [it appears we can't](https://security.stackexchange.com/questions/181921/disable-weak-cipher-for-google-cloud-app-engine-custom-domain-website)) then little point in having this on a custom policy to be honest and I'd revert it back to the default one so Google can manage keeping it up to date.

**Comment by bazzadp** [comment]
OK have reverted it back. As I say don't see point in that CDN being on custom policy when the main site isn't.

Closing this issue. It appears [Google App Engine don't allow you to manage this](https://security.stackexchange.com/questions/181921/disable-weak-cipher-for-google-cloud-app-engine-custom-domain-website). Sorry @cqueern !

**Comment by cqueern** [comment]
I wonder if we'll be able to disable support for TLS 1.0 and TLS 1.1 in time for next year's Almanac. Just a thought while we are in the "offseason"...

**Comment by tunetheweb** [comment]
As per above comment GCP doesn’t allow you to control this for app engine sites so we can’t turn this off for the almanac nor httprchive.org site (we can turn this off for the cdn.httparchive.org asset domain but little point on managing that manually if the main site can’t be changed).

**Comment by cqueern** [comment]
Makes sense. Thanks @tunetheweb .
