### ISSUE TITLE
Subdomains: Make beta the new www

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#33]
Progress on legacy redirects in #13.

- [x] Add an A record to the DNS for the `legacy` subdomain to resolve to the legacy web server
- [x] Add support for the `legacy` subdomain in the legacy web server's nginx and apache configs
- [x] Add SSL cert for the `legacy` subdomain
  - assigned to @pmeenan in https://github.com/HTTPArchive/httparchive/issues/132
- [x] Modify the beta server's 404 page to suggest the same URL on the legacy subdomain
- [x] Replace the `@` and `www` DNS A records to CNAME records, resolving to the new (beta) App Engine server at `ghs.googlehosted.com`
  - do this 4+ hours prior to launch to ensure that it propagates to DNS caches
- [x] Update all internal links to avoid 404s
  - eg stats/trends links on the forum

DNS settings:
- A		216.239.32.21
- A		216.239.34.21
- A		216.239.36.21
- A		216.239.38.21
- AAAA		2001:4860:4802:32::15
- AAAA		2001:4860:4802:34::15
- AAAA		2001:4860:4802:36::15
- AAAA		2001:4860:4802:38::15
- CNAME	ghs.googlehosted.com (www)

**Comment by rviscomi** [comment]
The legacy subdomain is up and running at http://legacy.httparchive.org/. SSL cert pending.

Sanity check: after replacing the DNS records to point to GAE it shouldn't matter that the legacy web server is still configured to handle @ and www subdomains, right? Because the DNS records (after 1 TTL) will never point to that server anyway. So is it necessary to clean up those configs or can they be left indefinitely?

**Comment by igrigorik** [comment]
No harm in keeping existing configuration — it's a noop.

**Comment by pmeenan** [comment]
legacy cert is complete - https://legacy.httparchive.org/

**Comment by rviscomi** [comment]
Added a TODO item to update internal links. Noticed on the forum that we're linking directly to stats/trends on the legacy site: 
![image](https://user-images.githubusercontent.com/1120896/37869684-7fb5aa38-2f92-11e8-944a-250367bdf19d.png)

**Comment by rviscomi** [comment]
Reduced the DNS TTL to 1h last night so no need to wait the full 4 hours now.

A, AAAA, and CNAME records for the root and www subdomain have been set.

**Comment by rviscomi** [comment]
Updated forum template to point to new (HTTPS) URLs.

![image](https://user-images.githubusercontent.com/1120896/38043984-7a3c9d0e-3286-11e8-971c-051721ea3fde.png)
