### ISSUE TITLE
New lens's

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/httparchive.org#377]
With https://github.com/HTTPArchive/bigquery/pull/115 I think we should have scope to add some new lens's.

Some thoughts I've had:
- Rankings - the top 1,000, top 10,000, top 100,000, top 1 million categories are [now available to use thanks to CrUX](https://developers.google.com/web/updates/2021/03/crux-rank-magnitude) so would be great to be able to filter there and see differences. Do we include all of them as lens's or only some? Probably top 1,000 or 10,000 are most interesting IMHO.
- CMS's - seems like there's [some banter](https://twitter.com/igrigorik/status/1415340002494402564?s=20) going on between Wix and Shopify. Our [own analysis](https://almanac.httparchive.org/en/2020/cms#top-cmss) says the top ones in order, are: Wordpress, Joomla, Drupal, Wiz, Squarespace and we only include the 1st and 3rd of those. We also didn't include Shopify in that chapters as a CMS - though [others do](https://w3techs.com/technologies/overview/content_management) and it's number two behind Wordpress so probably deserves a spot.
 
Should we drop Magento as a CMS as not as popular (I presume it was when first added)?

Other thoughts or lens's?

I think this could supplement the [Core Web Vitals Technology Report](https://dev.to/httparchive/introducing-the-core-web-vitals-technology-report-4pep) by exposing the other trends on our site, beyond the CWVs — though in a less comparable version than the CWV Tech Report.

The queries themselves are fairly simple and happy to put them together but opening this issue for discussion first. Are there any that are no brainers (top 1,000, and top 10,000 for example?) we should go ahead and just do, while we discuss the others?

**Comment by rviscomi** [comment]
+1 I think it makes sense to add ranking as a lens. That seems like a useful way to slice all metrics.

As for CMSs and the existing lenses, what are your thoughts if we:

- Create a CMS report that slices only the most interesting/relevant stats by top CMSs, similar to the data used by the CMS chapter.
- Extend the CWV Tech Report to include more lab metrics like page weight, Lighthouse stats, etc as CWV diagnostics to encourage exploration and discovery.
- Deprecate the three existing lenses as a long term goal.

**Comment by tunetheweb** [comment]
> +1 I think it makes sense to add ranking as a lens. That seems like a useful way to slice all metrics.

What’s your thoughts on what rankings to add? All of them seems a little OTT in my opinion - do we really need that level of slicing run every month? Or you think add them all anyway?

> As for CMSs and the existing lenses, what are your thoughts if we:
> 
> * Create a CMS report that slices only the most interesting/relevant stats by top CMSs, similar to the data used by the CMS chapter.
> * Extend the CWV Tech Report to include more lab metrics like page weight, Lighthouse stats, etc as CWV diagnostics to encourage exploration and discovery.
> * Deprecate the three existing lenses as a long term goal.

I’m in two minds.

On one hand I’m not sure why they should get special treatment over say JavaScript frameworks, or Bootstrap. And maybe the technology report is the better place for slicing like this?

On other hand Wordpress is a HUGE amount of the Internet so maybe it still deserves a lens? And how do we define “the most interesting stats”? Your initial [lazy loading tweet](https://twitter.com/rick_viscomi/status/1344380340153016321?s=21) for example was very easy to spot after adding the graph, which then led to your recent work/blog post. Then again, there’s plenty of examples of similar discoveries that required reliving into the data and wasn’t exposed as a regular graph.

On balance I probably say deprecate them as you suggest and switch lenses to being ranking only.

I think a desperate CMS report is a good idea, but not a necessary step before deprecation of the lens’s. The CWV Technology report has the most important t stats for now - though would be good to expand those in future.

**Comment by tunetheweb** [comment]
Closing this as added ranking lenses.
