### ISSUE TITLE
www can't load data from CDN

### ISSUE THREAD

**Issue by dracos** [HTTPArchive/httparchive.org#38]
I followed a link to https://www.httparchive.org/reports/state-of-the-web (actually to http://www.httparchive.org/interesting.php , thanks for redirecting) and the graphs don't load because the CDN only allows https://httparchive.org/ CORS. I don't know whether you'd want to redirect www to bare, or add the www to the CORS allow header, but thought I'd let you know.

**Comment by rviscomi** [comment]
Confirmed bug.

To fix:

- [ ] add `https://www.httparchive.org` and `http://www.httparchive.org` to [CORS whitelist](https://github.com/HTTPArchive/bigquery/blob/master/config/storage-cors.json)
- [ ] run `gsutil cors set config/storage-cors.json gs://httparchive` (by admin with write access)

@dracos could you submit a PR for the whitelist?
