### ISSUE TITLE
Desktop styles broken

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#392]
The home and report pages appear to have broken styles. On an ~1100px width viewport, content is vertically stacked when it should be horizontal. This seems like a bad media query or something similar where desktop is being incorrectly styled as mobile. @tunetheweb could you see if this is related to some of your recent changes?

![image](https://user-images.githubusercontent.com/1120896/127033937-cde04cfa-8ad1-421f-bed2-cb55de1ed213.png)

**Comment by tunetheweb** [comment]
Fixed. Sorry about that. Fixing some overflow issues identified by Lighthouse (I hate bouncing web pages on mobile!!!).

**Comment by rviscomi** [comment]
Thanks for the quick fix!
