### ISSUE TITLE
Prototype a JS report

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#4]
Possible topics:

- [x] bytes per page
- [ ] bytes per request
- [x] number of requests
- [ ] third-party libraries
    - [ ] versions
    - [x] vulnerabilities
        - depends on https://github.com/HTTPArchive/httparchive/issues/87 and https://github.com/GoogleChrome/lighthouse/pull/2372
- [ ] compression used
- [ ] last modified
- [x] execution time
- [ ] code coverage
    - depends on #6 
- [x] Service Worker usage
    - depends on https://github.com/HTTPArchive/httparchive/issues/87
- [ ] modularization
    - depends on #5

**Comment by igrigorik** [comment]
Let's identify the dependencies for these as well? E.g. vulnerabilities work is blocked on Lighthouse. Ditto for code coverage? It'd be nice to cross-link these so we can track progress across these projects.

**Comment by rviscomi** [comment]
Cleaning up old issues. JS report exists.
