### ISSUE TITLE
Investigate missing Wasm response bodies

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#416]
The Wasm chapter of the 2021 Web Almanac is planning to analyze the Wasm response bodies. However, there's a discrepancy between the number of Wasm resources in the `[summary_]requests` tables and `response_bodies`.

```sql
SELECT
  COUNT(DISTINCT url)
FROM
  `httparchive.summary_requests.2021_07_01_*`
WHERE
  ext = 'wasm' OR
  mimeType = 'application/wasm'
```

There are 2,453 requests with a file extension or MIME type of Wasm.

```sql
SELECT
  COUNT(DISTINCT url)
FROM
  `httparchive.almanac.summary_response_bodies`
WHERE
  date = '2021-07-01' AND
  (ext = 'wasm' OR mimeType = 'application/wasm')
```

There are only 112 response bodies with the same conditions.

**Comment by tunetheweb** [comment]
Don't we exclude binary bodies? Don't know WASM well enough but are they always delivered as text?

```sql
SELECT
  ext,
  mimeType,
  COUNT(DISTINCT url) as freq
FROM
  `httparchive.summary_requests.2021_07_01_*`
WHERE
  ext = 'wasm' OR
  mimeType = 'application/wasm'
GROUP BY
  ext,
  mimeType
ORDER BY
  freq DESC
```

ext | mimeType | freq
-- | -- | --
wasm | application/wasm | 1170
wasm | application/octet-stream | 526
wasm |   | 477
  | application/wasm | 70
wasm | text/plain | 58
wasm | text/html | 57
dll | application/wasm | 45
wasm | binary/octet-stream | 24
gz | application/wasm | 15
br | application/wasm | 7
wasm | application/json | 6
wasm | application/xml | 3
json | application/wasm | 2
data | application/wasm | 2
gif | application/wasm | 2
php | application/wasm | 2
pck | application/wasm | 1
wasm | application/binary | 1
wasm | application/javascript | 1
wasm | text/xml | 1
wasm | application/webassembly | 1
wasm | application/force-download | 1
wasm | application/kaas | 1
wasm | application/wasm .wasm | 1
wasm | text/hpb | 1
wasm | application/octet-stream | 1

58 `text/plain  + 57 `text/html` makes 114 🤔

**Comment by RReverser** [comment]
> Don't know WASM well enough but are they always delivered as text?

They are never text, they are binary resources, although it's common for legacy backends to deliver them with invalid mime type (which still doesn't affect their usage).

**Comment by tunetheweb** [comment]
Well there's the issue then. For space reasons, and cause binary files typically aren't that useful to store, we only save text resources to response bodies (see https://github.com/HTTPArchive/bigquery/pull/125/files).

Not sure if the original response bodies are still there and can be uploaded separately? Or access can be provided outside of BigQuery which is probably better. @rviscomi ?

**Comment by rviscomi** [comment]
Ah, yes @tunetheweb is correct. I was taken in by the few Wasm response bodies that I forgot that they aren't expected to be there in the first place.

@RReverser what this means for the Wasm chapter is that we shouldn't rely on the WPT output (in BigQuery or Cloud Storage) for Wasm response bodies. Unfortunately, the only way to get the files would be to manually download them, which would be time/resource intensive. It may still be feasible if you're interested to put in the effort, bearing in mind that we only have about a month until the analysis is expected to be completed.

**Comment by RReverser** [comment]
> Unfortunately, the only way to get the files would be to manually download them, which would be time/resource intensive.

Given the number of files, it shouldn't be too bad, and that was in fact my original plan, but you suggested we should do all the parsing/queries via JS UDF in BigQuery itself which led me slightly down this rabbit hole :)

Going back to local parsing sounds fine.

Although in the future I think we might want to include Wasm contents in future crawls anyway. Most binary resources might be not so useful to parse, but Wasm is statically analyzable and, as number of Wasm files out there grows, we might want to eventually move parsing to BigQuery for future almanac versions anyway.

**Comment by rviscomi** [comment]
> but you suggested we should do all the parsing/queries via JS UDF in BigQuery itself which led me slightly down this rabbit hole :)

Sorry 😞 

I've exported ~8k combos of pages and Wasm URLs from the July 2021 crawl to the Wasm chapter spreadsheet:

https://docs.google.com/spreadsheets/d/1IMa2SbdQgshb4pGWF1KOh9s4zMtLbRymWZGYjdaatXY/edit#gid=1098899986

```sql
SELECT DISTINCT
  _TABLE_SUFFIX AS client,
  rank,
  wptid,
  respSize,
  page,
  url
FROM
  `httparchive.summary_requests.2021_07_01_*`
JOIN
  (SELECT url AS page, pageid, rank, wptid, _TABLE_SUFFIX FROM `httparchive.summary_pages.2021_07_01_*`)
USING
  (_TABLE_SUFFIX, pageid)
WHERE
  ext = 'wasm' OR
  mimeType = 'application/wasm'
ORDER BY
  rank,
  wptid
```

To reiterate, this is a superset of the 2.5k list of distinct Wasm URLs. It will include duplicate Wasm URLs if it's included on multiple pages, but not if it's included multiple times on the same page. I did it this way to help with the analysis later, for example "_X% of pages that include Wasm use feature XYZ_".

Given that this is no longer a pipeline issue, I'll close this issue.

**Comment by RReverser** [comment]
Thanks!

Should I open a separate issue for

> Although in the future I think we might want to include Wasm contents in future crawls anyway. Most binary resources might be not so useful to parse, but Wasm is statically analyzable and, as number of Wasm files out there grows, we might want to eventually move parsing to BigQuery for future almanac versions anyway.

?

**Comment by rviscomi** [comment]
@pmeenan would a Wasm response body exemption be a FR against the WPT repo?

**Comment by pmeenan** [comment]
Maybe. It could be worth considering if you actually want the raw files in BQ, cloud storage, or if the analysis could be done on the agent side and extracted information uploaded (kind of like we do for fonts, images, and other "binary" formats).

**Comment by RReverser** [comment]
> kind of like we do for fonts, images, and other "binary" formats

I think Wasm is very different from other binary formats, because in case of those resources we're interested only in metadata and don't touch the main content (>95%) of the file, while in Wasm we do want to analyze _everything_.

Personally I'd be leaning towards uploading the whole Wasm to make it easier to extract and play with interesting stats on the fly.

**Comment by rviscomi** [comment]
@pmeenan does the Wasm omission happen on the WPT side, or is there some logic in the HA agents/pipeline that drops all binaries? I think for the purposes of enabling this kind of analysis in the future, including the Wasm response bodies in BQ and Cloud Storage would be needed. I think it only adds 2 GB per crawl.

**Comment by pmeenan** [comment]
It is on the WPT side.  There is logic that only stores response bodies with the test result for "text" resources.  Where did the 2GB number come from? Is that roughly the size of all wasm responses currently in the crawl?

The logic that does the filtering is [here](https://github.com/WPO-Foundation/wptagent/blob/master/internal/devtools.py#L730).

It looks like wasm responses are currently base-64 encoded by dev tools when they are retrieved so it fails the non-text check.

Collecting the body itself should be easy enough but other parts of WPT expect that the currently collected bodies are text so there will likely need to be more changes (and the har pipeline would need to figure out how to store them or make them available).

**Comment by rviscomi** [comment]
2 GB came from this query

```sql
SELECT SUM(raw_size) / 1024 / 1024 / 1024 AS gb FROM
  `blink-httparchive-research.rreverser2.wasms`
```

**Comment by RReverser** [comment]
Probably worth noting that that table contains deduplicated contents by their hash; I'm guessing it should be possible to perform similar content-addressable storage in HA, but, if not, the total size would be ~3x of that (6 GB).

**Comment by RReverser** [comment]
I'm guessing content-deduplicated storage would actually be best because it would allow savings not only within each crawl, but also across month-to-month crawls as well as across desktop/mobile split. The total savings are likely to be significant, as most websites will contain same Wasm files from one crawl to another.

**Comment by RReverser** [comment]
Should we raise a dedicated issue somewhere so that we don't lose discussion in this closed one?

**Comment by rviscomi** [comment]
Tracking this upstream in WebPageTest: https://github.com/WPO-Foundation/wptagent/issues/437

**Comment by pmeenan** [comment]
Though, if the goal is to have de-duped storage of common bodies, that's something that will also need to be tracked on the HTTP Archive side separately.

**Comment by RReverser** [comment]
> Tracking this upstream in WebPageTest: [WPO-Foundation/wptagent#437](https://github.com/WPO-Foundation/wptagent/issues/437)

Oh, right, sorry 🤦‍♂️
