### ISSUE TITLE
robots.txt is not valid

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#422]
Per https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fhttparchive.org%2F#seo

> robots.txt is not valid
>Lighthouse was unable to download a robots.txt file

**Comment by tunetheweb** [comment]
Looks perfectly valid to me. Raise a bug with Lighthouse?

**Comment by rviscomi** [comment]
Agreed, seems like a LH issue

**Comment by tunetheweb** [comment]
Search Console thinks it's fine too:

![image](https://user-images.githubusercontent.com/10931297/131532331-285bbbc0-c99f-4ad9-a624-9617061aebc9.png)

**Comment by brendankenny** [comment]
it looks like a PSI error. CLI Lighthouse has no problem fetching the file, even downgrading to the current LH version deployed on PSI.

**Comment by rviscomi** [comment]
FWIW this test came from web.dev/measure

**Comment by brendankenny** [comment]
PSI/PSI API, yeah. I can only recreate the problem there. Looks like some other people might be having the same issue: https://github.com/GoogleChrome/lighthouse/issues/12936#issuecomment-908619293

**Comment by rviscomi** [comment]
Ah ok, thanks
