### ISSUE TITLE
Wappalyzer detecting too many technologies in some cases 

### ISSUE THREAD

**Issue by rockeynebhwani** [HTTPArchive/httparchive.org#425]
@pmeenan   - Hope you saw the issue - https://github.com/AliasIO/wappalyzer/issues/4005 (Please see last few comments on this issue). 

Though the original issue suggests that issue is with Chrome extension but we are seeing this issue for our crawl also. @rviscomi  suggested to create this issue so that you can bring this change in HTTPArchive branch of Wappalyzer. 

At this stage, I don't know how many origins this issue impacts but it will be good to bring this change and see if you can include in Sep crawl (which just started).

@tunetheweb  - FYI

**Comment by pmeenan** [comment]
Just merged and it is rolling out over the next hour.
