### ISSUE TITLE
Investigate 0% pctVuln as of July 1

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#46]
The percent of vulnerable JS dropped to 0 in the most recent release.

![image](https://user-images.githubusercontent.com/1120896/42780519-6f68d438-8911-11e8-92d1-af24575ecf5f.png)

https://httparchive.org/reports/state-of-the-web?start=2018_06_15&end=2018_07_01#pctVuln

**Comment by pmeenan** [comment]
Probably a parsing change because of the switch to lighthouse 3 (if I had to guess).  The json structure changed.

**Comment by rviscomi** [comment]
Exactly. The `score` property changes from true/false to 1/0. I'll update the query to handle either.
