### ISSUE TITLE
1.4 TB (65%) increase in storage size of lighthouse tables after 8.0

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#476]
Looking at the [BQ dashboard](https://datastudio.google.com/u/0/reporting/1jh_ScPlCIbSYTf2r2Y6EftqmX9SQy4Gn/page/Z0Bg), I noticed an increase in the number of GB per `lighthouse` table. In August, before LH 8.0, the table weighed 2,125 GB. Now the October table weighs 3,508 GB.

Since the number of rows has not increased substantially, the extra data must be in the report JSON itself. We should check for things like base64-encoded images or large blocks of user-generated content and omit them from the dataset during the Dataflow pipeline step.

![image](https://user-images.githubusercontent.com/1120896/139864741-f43d239a-2bdf-4251-bfbe-2e6922dfc22d.png)

**Comment by brendankenny** [comment]
This was https://github.com/GoogleChrome/lighthouse/pull/12645 released in [Lighthouse 8.4.0 on September 8th](https://github.com/GoogleChrome/lighthouse/releases/tag/v8.4.0).

Looks like the HTTP Archive runner uses `--skip-audits screenshot-thumbnails final-screenshot` (or the JS option equivalent) which before that PR would implicitly filter out the large, base64-encoded `full-page-screenshot` just by having any `--skip-audits` set.

That PR made it so you have to explicitly filter it out which is less surprising behavior (and desired by multiple downstream projects) but is a surprise to anyone saving LHRs and expecting unchanged storage behavior. We try to warn about large increases in report file size but didn't anticipate the effect on HTTP Archive this time. Sorry about that!

To restore the old behavior, add `full-page-screenshot` to the other skipped audits for the HTTP Archive runner. I'm happy to open a PR but I always forget where those options are set :)

**Comment by brendankenny** [comment]
The downside of filtering out `full-page-screenshot` is that all the element images/thumbnails in the report are clipped areas from the single large `full-page-screenshot`, so anyone looking at an html report from the JSON stored in BQ won't have working images. The report should still work fine (it'll give fallback references like css selectors so elements will still be identifiable) but it'll be less useful. OTOH $5-10 extra per query is a lot :)

**Comment by rviscomi** [comment]
Thanks for tracking that down!

@pmeenan could you add that skipped audit? I also looked for that config on GitHub but it may not be checked in.

**Comment by rviscomi** [comment]
> anyone looking at an html report from the JSON stored in BQ won't have working images

I hadn't realized that this config is baked into WPT. I can imagine it'd be nice to see the images in a one-off LHR created from WPT, but for HA purposes we're mostly interested in aggregate results and we don't need to inspect individual reports. Maybe something to consider in the future is an HA-specific config.
