### ISSUE TITLE
Add ranking info to Chrome Status dashboard

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#482]
The [Blink feature usage](https://datastudio.google.com/u/0/reporting/1M8kXOqPkwYNKjJhtag_nvDNJCpvmw_ri/page/tc5b) dashboard embedded on chromestatus.com is sourced from HTTP Archive's `blink_features` dataset. It would be useful to slice the feature data by rank (site popularity).

**Comment by max-ostapenko** [comment]
Duplicate of https://github.com/HTTPArchive/dataform/issues/25
