### ISSUE TITLE
Migrate and update Getting Started guide

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#52]
The [Getting Started](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/docs/bigquery-gettingstarted.md) guide written by @paulcalvano lives in the legacy repository. It was written before the new BigQuery UI started rolling out to users, so the workflow may not be applicable to those users anymore.

We should move the documentation out of the legacy repo and into this one where people can more easily find it. We can implement it similar to the FAQ, where it is a markdown file readable on GitHub and also rendered as HTML on the website.

We should also update the docs to handle both the new and old BigQuery UI (until the old UI is deprecated).

**Comment by paulcalvano** [comment]
I'd be happy to work on this one.

**Comment by paulcalvano** [comment]
I'm working on updating the guide, and ran into a small issue on the new BigQuery Beta UI.  I don't see any way that we can add the httparchive project via the Beta UI.   

In the classic UI I can switch to a project and enter httparchive to add the tables - 
![image](https://user-images.githubusercontent.com/7459458/45260513-af864700-b3b7-11e8-81d6-0305e75c10e1.png)


But I don't see any option to do this in the Beta UI.   Am I missing something here, or should we advise users to switch to the classic UI to add the httparchive project for now?

![image](https://user-images.githubusercontent.com/7459458/45260497-6930e800-b3b7-11e8-81e2-a502b24dc53c.png)

**Comment by rviscomi** [comment]
Yeah I'm not a fan of the discoverability in the new UI. The only workaround I know of is to append `p=httparchive` in the URL so that the project is added to the workspace.

**Comment by max-ostapenko** [comment]
The guide was migrated to har.fyi https://github.com/HTTPArchive/httparchive.org/pull/875
