### ISSUE TITLE
301 redirect all beta subdomain requests

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#56]
Return a 301 Moved Permanently response to all requests for beta.httparchive.org. The location should be the same URL minus the beta subdomain.

It's the same content behind both URLs but we may remove the beta subdomain at some point and don't want any old links floating around.

**Comment by malchata** [comment]
If 301 redirects will take some time to test, we could use `<link rel="canonical">` on the beta subdomain to point to the primary domain to deal with any SEO-related issues.
