### ISSUE TITLE
Bigquery: Add missing response bodies data for 2020 November-2021 June (Desktop and Mobile)

### ISSUE THREAD

**Issue by gezmondo-cyber** [HTTPArchive/httparchive.org#592]
The httparchive/response_bodies tables on Bigquery should be monthly for 2020-2021.
Several tables for the period 2020.11-2021.06 seem to be missing.

Could you please upload them to Bigquery?

![image](https://user-images.githubusercontent.com/105175794/167316272-c877e442-a255-4529-a823-d07b64ceb60c.png)

**Comment by rviscomi** [comment]
Thanks for filing this! Regenerating the `response_bodies` tables should be doable, but given the ongoing infrastructure work it may be lower priority.

**Comment by Jayjay1488** [comment]
Hey this jayjau 1488 I need someone to call me or email how to get me money please jamiechimiledki19@gmail. Com orjaimechimiledki@gmail. Com

**Comment by Jayjay1488** [comment]
![Screenshot_20230625-014409](https://github.com/HTTPArchive/httparchive.org/assets/87629434/cf4032a5-79c8-4ac6-8910-654e9e3797cd)
![Screenshot_20230625-014348](https://github.com/HTTPArchive/httparchive.org/assets/87629434/eb521a7b-eb1d-4e37-8c62-0787f5b08af6)
![Screenshot_20230625-013148](https://github.com/HTTPArchive/httparchive.org/assets/87629434/de26b314-3bf8-41bb-a691-0f956b0eaa0a)
![Screenshot_20230625-014602](https://github.com/HTTPArchive/httparchive.org/assets/87629434/30413427-2bd6-428e-be90-a7e34a3f57b2)
![Screenshot_20230625-014150](https://github.com/HTTPArchive/httparchive.org/assets/87629434/5e2a8fb2-c3a7-42fb-8fe0-e4d8c607f1cb)
![Screenshot_20230625-013816](https://github.com/HTTPArchive/httparchive.org/assets/87629434/e2f63491-0389-424a-91f0-02a398e09af6)
![Screenshot_20230625-001042](https://github.com/HTTPArchive/httparchive.org/assets/87629434/51728f83-0826-49f4-8c13-0583faeb93d3)
![Screenshot_20230625-002844](https://github.com/HTTPArchive/httparchive.org/assets/87629434/68c092d7-6638-4d3c-8700-b4f624038870)
![Screenshot_20230625-014011](https://github.com/HTTPArchive/httparchive.org/assets/87629434/11768fe9-5e63-4204-a4de-2714317e602e)
![Screenshot_20230624-233930](https://github.com/HTTPArchive/httparchive.org/assets/87629434/20e7c979-bf94-4dcc-b20c-42a6ca1e1200)
![Screenshot_20230625-014156](https://github.com/HTTPArchive/httparchive.org/assets/87629434/f754678b-4058-48d1-a06b-5979980ef5d7)
![Screenshot_20230625-013135](https://github.com/HTTPArchive/httparchive.org/assets/87629434/124154e9-7ff7-47c4-9680-95118b322e6b)
 
![Screenshot_20230625-014139](https://github.com/HTTPArchive/httparchive.org/assets/87629434/8b1e2e6a-f6b1-4e12-bd57-60d7cf2bf903)
![Screenshot_20230625-014251](https://github.com/HTTPArchive/httparchive.org/assets/87629434/ce21998e-58c7-4340-8150-93826d62dda5)
P
![Screenshot_20230625-013957](https://github.com/HTTPArchive/httparchive.org/assets/87629434/7a3d53c5-7d69-444f-9347-a58038107b72)
l
![Screenshot_20230625-014555](https://github.com/HTTPArchive/httparchive.org/assets/87629434/63aae564-c83f-402a-a585-d351c533994c)
![Screenshot_20230625-014438](https://github.com/HTTPArchive/httparchive.org/assets/87629434/d4c4984e-b153-4781-8d85-f58e8c8a2dac.  Please help me

**Comment by max-ostapenko** [comment]
@rviscomi this is still relevant. Do we skip it in the backfill?
If yes, probably we should just close it after 2 years?

**Comment by max-ostapenko** [comment]
And do you remember why did the number of rows explode there?
![Screenshot 2024-10-19 at 02 19 30](https://github.com/user-attachments/assets/e7857f9d-0ffd-401d-a0d4-bac8fe224ba3)

**Comment by tunetheweb** [comment]
I believe images were accidentally included for a period instead of just text response bodies. We shoudl exclude these in the port over to `all`.

See also: https://github.com/HTTPArchive/httparchive.org/issues/225
