### ISSUE TITLE
CrUX INP graph

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/httparchive.org#595]
Would it be useful to add an [INP](https://web.dev/inp/) graph to our [CrUX report page](https://httparchive.org/reports/chrome-ux-report)? Or at least the SQL to query it, with graph to follow (after we have at least a few months data)?

Would allow people to track trend and or filter by our lenses.

Or too early?

FYI: @anniesullie @mmocny

**Comment by rviscomi** [comment]
Yeah SGTM. FWIW I've also added it to [cwvtech.report](https://cwvtech.report/).

**Comment by tunetheweb** [comment]
This is live now: https://httparchive.org/reports/chrome-ux-report#cruxFastInp

**Comment by rviscomi** [comment]
Nice work, great to have this added to the report!

Want to also share a tweet about it?

**Comment by tunetheweb** [comment]
https://twitter.com/httparchive/status/1525227735492214787?s=21&t=q6sIUJHk_du3sZP2vPvgTg
