### ISSUE TITLE
Capture JS/CSS code coverage metrics

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#6]
See https://developers.google.com/web/updates/2017/04/devtools-release-notes#coverage

@pmeenan is this something we can get directly from WPT if the right bits are fiddled?

**Comment by rviscomi** [comment]
@pmeenan is there a way to get code coverage info in the HAR data?

**Comment by pmeenan** [comment]
Yep, I've been peeking at the profiler code and should be able to get rough coverage data (function/block level accuracy). Any more granular than that turns off the v8 code optimizations and kills perf.  I can probably get it added before the next crawl.

Not sure we can caveat the data but analysis will have to be with a grain of salt.  The coverage would just cover the code (and css) that was used to load the page.  If the code is needed to handle interactions, scrolling, etc it is still important to load but would be considered part of the dead code.

**Comment by paulcalvano** [comment]
I believe the code coverage details are in the lighthouse test results already.

**Comment by paulcalvano** [comment]
Actually it looks like just the css coverage details are in the lighthouse reports.  

```   "unused-css-rules": {
      "score": 0,
      "displayValue": "Potential savings of 178 KB (~1,070 ms)",
      "rawValue": 1070,
      "extendedInfo": {
        "value": {
          "wastedMs": 1070,
          "wastedKb": 178,
          "results": [
```


For example, you can extract the wastedKb with 
`JSON_EXTRACT_SCALAR(report, "$.audits.unused-css-rules.extendedInfo.value.wastedKb")`

**Comment by tunetheweb** [comment]
Closing as both available in Lighthouse now
