### ISSUE TITLE
May 2022 Loading Speed Graphs show huge improvement on previous months.

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/httparchive.org#605]
Migrated from: https://github.com/HTTPArchive/httparchive.org/issues/601#issuecomment-1145675792

> @pmeenan any thoughts on the massive performance improvements on these graphs for mobile: https://httparchive.org/reports/loading-speed

Response from @pmeenan :

> My first guess/worry was going to be the CPU throttling but looking at the mobile template for tests, the throttling is still configured for 8x and the bandwidth is set to the 4G speeds.
> 
> I'm going to see if I can spot check a few pages to see if anything jumps out. Could be that the CPU throttling in Chrome broke again (or that I did something wrong on the switch to the new pipeline)

**Comment by pmeenan** [comment]
Looking at the Javascript CPU boot-up time graph, it looks like JS is taking around the same amount of time so it may not be CPU throttling.

**Comment by tunetheweb** [comment]
> Looking at the Javascript CPU boot-up time graph, it looks like JS is taking around the same amount of time so it may not be CPU throttling.

That JS boot up time comes from Lighthouse though. Think rest are from `pages` table. So could be LH throttling is fine, but non-LH throttling is not?

**Comment by pmeenan** [comment]
I think it's the connectivity settings.  I thought we were using 4G for mobile testing but comparing cnn in [April](https://webpagetest.httparchive.org/result/220401_MxS_1HK9/) vs [May](https://webpagetest.httparchive.org/result/220512_Mx0_4FE/) it looks like the TBT and CPU times are all fine but the requests themselves are faster (and the April test is labeled as 3G).

We were SUPPOSED to be testing at 4G according to the [hack in the legacy batch code](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/bulktest/batch_lib.inc#L94) but it looks like it didn't actually work.

At this point we can either log the change to 4G in the change log or change the configs back to 3G and re-run the June crawl.

**Comment by pmeenan** [comment]
FWIW, Lighthouse always runs at "3G Fast" independent of the WPT settings.
