### ISSUE TITLE
Missing histogram data for Nov 15, 2010

### ISSUE THREAD

**Issue by alex-bender** [HTTPArchive/httparchive.org#612]
![image](https://user-images.githubusercontent.com/3628862/174446813-a1fb4aac-7bc1-4b70-95b3-94afc2c0a92a.png)
https://cdn.httparchive.org/reports/top1k/2010_11_15/speedIndex.json

```18:58:09.028 Error loading histogram data https://cdn.httparchive.org/reports/top1k/2010_11_15/bootupJs.json 
Response { type: "cors", url: "https://cdn.httparchive.org/reports/top1k/2010_11_15/bootupJs.json", redirected: false, status: 404, ok: false, statusText: "Not Found", headers: Headers, body: ReadableStream, bodyUsed: false }
histogram.js:1:4233
```

**Comment by tunetheweb** [comment]
The ranking lenses (top 1000, 10000… 1 million) were only added from May 2021 so didn’t exist for 2010.

**Comment by rviscomi** [comment]
One could argue that we shouldn't show start/end options for dates that we know are not supported by the lens. For example, some metrics provide a min/max date when we know about its availability window. Perhaps we should do the same for lenses.

https://github.com/HTTPArchive/httparchive.org/blob/5a63e50f1beda49755e98e712fa5ad6adfa1a4b5/config/reports.json#L118-L125

**Comment by tunetheweb** [comment]
Potentially, but can also result in fighting the GUI and confusing users.

For example I'm in 10k lens (only available for 2022). I want as much WordPress data as possible. If the date was filtered, I might not realise there is a lot more than for 10k, and at the very least there's two steps.

So both ways have their downfalls.

Maybe a better option would potentially be to leave the date pickers alone, but use an error message (where it's less obvious what the limits are than for the timeseries):

> "Error: Histograms for 10k are only available from April 2022"

**Comment by alex-bender** [comment]
as a general rule, I suppose, if error could be precalculated\predicted, it's better to notify user beforehand

**Comment by rviscomi** [comment]
Reopening so we can continue thinking through our options

**Comment by alex-bender** [comment]
would it be possible to change it from dropdown to choicefiled?

**Comment by alex-bender** [comment]
sure, will try to do that tomorrow

**Comment by alex-bender** [comment]
Hey, thanks for the ping. Looks like I can win longest stalled issue challenge.
Could you please describe a bit more what should be done since I'm not fully understand what's exactly should be done?

If there should be error message or notification, where should it be placed. In what case should it be displayed and so on..
