### ISSUE TITLE
Add a change log entry about response bodies in May 2022

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#614]
Due to a crawl config error, we don't have response bodies in the May 2022 dataset. Add this to the change log.

**Comment by tunetheweb** [comment]
This doesn't affect any of the graphs. I wonder should we have an "include-in-graphs" flag we can set to false in these instances so it's only include [in the FAQ](https://httparchive.org/faq#what-changes-have-been-made-to-the-test-environment-that-might-affect-the-data)? Or would that be too confusing for people?

**Comment by tunetheweb** [comment]
Was easy enough to do so added that in #615
