### ISSUE TITLE
Enable unused JS Lighthouse audit

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#62]
The "Unused JavaScript" Lighthouse audit is not enabled by default.

Adjust the Lighthouse config in our WebPageTest agents to enable this audit.

See the note in the [LH docs](https://developers.google.com/web/updates/2018/05/lighthouse#unused_javascript) for more info:

> Note: This audit is off by default! It can be enabled in the Node CLI by using the lighthouse:full configuration profile.

@pmeenan can you look into this?

cc @patrickhulce

**Comment by pmeenan** [comment]
@patrickhulce is there a perf impact to enabling it? I.e. does it use the high or low precision trace events (where high precision disables optimization)?  I wouldn't want to enable it if it made the performance audits invalid.

________________________________

**Comment by brendankenny** [comment]
There is the possibility of significant overhead, so we don't run it in the performance-measuring pass. If you use the [full config](https://github.com/GoogleChrome/lighthouse/blob/f1fee4e38569e08180817994754f0f5998b6a2b2/lighthouse-core/config/full-config.js) it adds an additional page reload to get the coverage data.

We have questioned the overhead assumption in the past, though, and want to reevaluate if there's a way to run it without introducing another pass and without affecting the performance numbers. The overhead might be more significant in the webpagetest-throttled case than the lantern one, however.

**Comment by pmeenan** [comment]
I'll have to check the impact that an extra pass adds.  Should be less than
10% but we're running the crawl pretty hot right now with the CrUX list and
that may add a day or two to the overall crawl.

**Comment by rviscomi** [comment]
Duplicate of #6
