### ISSUE TITLE
Link in gettingstarted_bigquery.md leads to error

### ISSUE THREAD

**Issue by davidsgrogan** [HTTPArchive/httparchive.org#625]
Step 6 in https://github.com/HTTPArchive/httparchive.org/blob/main/docs/gettingstarted_bigquery.md has a link to
 https://console.cloud.google.com/bigquery?p=httparchive&d=httparchive&page=dataset . But that leads to the error message below. I'm not sure how to proceed.

Note that I'm a googler so the resulting URL starts with "pantheon". I don't know if that matters.
<img width="837" alt="Screen Shot 2022-07-21 at 5 21 42 AM" src="https://user-images.githubusercontent.com/1801875/180212566-5db1aa53-9043-40ed-a248-865d2b11ff1d.png">

**Comment by tunetheweb** [comment]
Could you try this link?: https://console.cloud.google.com/bigquery?p=httparchive&d=all&page=dataset
(it'll redirect to the internal version, but more important is if it works).

**Comment by davidsgrogan** [comment]
This is what I get from that link. So I guess it works, but I don't have the list of tables in the left sidebar like step 7 shows. I'm not very bigquery-literate though.
<img width="1351" alt="Screen Shot 2022-07-21 at 5 43 38 AM" src="https://user-images.githubusercontent.com/1801875/180216190-1b689cbd-0205-49e8-8c78-72f3e6d2cade.png">

**Comment by tunetheweb** [comment]
That wasn't quite right either and a bit more complicated than that. Updated guide in #626 and David's confirmed he has access now.
