### ISSUE TITLE
Incorrect units in chart titles.

### ISSUE THREAD

**Issue by kevincox** [HTTPArchive/httparchive.org#643]
Looking at https://httparchive.org/reports/state-of-the-web I see that all of the chart titles say "KB" when a few of the underlying queries that I sampled are actually computing the size in KiB. This is inaccurate and confusing. Probably the titles should be updated to say KiB to accurately reflect the data.

**Comment by tunetheweb** [comment]
"Incorrect" is a bit strong IMHO, and uptake of KiB is still not great in general. I think [this answer](https://ux.stackexchange.com/a/13850) still stands to be honest - 7 years later!

A lot of our audience is probably technical enough to understand the difference (and may even appreciate the greater clarity of using KiB), but the charts are also widely shared by others who may not have this understanding and may find KiB confusing.

Thoughts @rviscomi / @pmeenan / @paulcalvano ?

**Comment by kevincox** [comment]
I agree that incorrect is a bit strong but it would be nice that reading the graphs I can be sure what I am seeing instead of having to guess. Although at the sizes presented on page (small numbers of MiB) it doesn't make much difference either way.

Maybe if you want to keep this KB add some title-text or other indicator that species the unit somewhere so that readers don't need to wonder?

**Comment by rviscomi** [comment]
+1 to the reply in @tunetheweb's link and standardizing on 1 KB = 1024 bytes. If needed we could add something to our FAQ.

**Comment by max-ostapenko** [comment]
Seems this was fixed across the CWV and other reports - using 1024 division with bytes, KB and MB labels.
