### ISSUE TITLE
Authenticate gcloud with service account

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#66]
Need to resolve this warning:

> ~/python-venv/lib/python2.7/site-packages/google/auth/_default.py:66: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
>   warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

**Comment by max-ostapenko** [comment]
Seems outdated, will close it.
Please, reopen if needed.
