### ISSUE TITLE
Seems impossible to get a 10 year chart or table

### ISSUE THREAD

**Issue by mgifford** [HTTPArchive/httparchive.org#770]
So if I want to see the growth over a decade in page weight, I should be able to go here:
https://httparchive.org/reports/page-weight?lens=top10k&start=2013_08_01&end=latest&view=list

It should show me the data from Aug 1, 2013 till now, it should work. Sadly, doesn't seem to work in the chart or the table. I can't seem to get information earlier than 2021.

<img width="1210" alt="Screenshot of page weight chart and exposed table" src="https://github.com/HTTPArchive/httparchive.org/assets/116832/8ad81f04-0bb6-4788-a207-a7f92ed8e412">

<img width="1225" alt="Screenshot of the Javascript chart and exposed table" src="https://github.com/HTTPArchive/httparchive.org/assets/116832/5ba55244-9ef8-4827-89cb-2548bd9e01cd">

**Comment by rviscomi** [comment]
Try removing the "Top 10,000" lens. Ranking data was only made available in the upstream Chrome UX Report dataset relatively recently, so we're unable to filter older crawls.

Here's a working example using all websites: https://httparchive.org/reports/page-weight?start=earliest&end=latest&view=list#bytesTotal
