### ISSUE TITLE
Improve tablet navigation

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#78]
See https://twitter.com/janssenstom/status/1036171871237091329?s=19

Difficult to navigate to subitems.

**Comment by stephanmax** [comment]
Do you mind me working on this?

This poses a quite tricky UI question... What would be a good solution for you, @rviscomi? I believe that on-hover UI actions are an anti-pattern. What do you think about making the dropdown open-on-click and adding an extra link inside the dropdown (at the top) that serves as a link to the index page of the category (e.g. `/reports`)?

**Comment by rviscomi** [comment]
@stephanmax go for it! Thanks! Your suggestion SGTM. For the Reports menu we can add an "All Reports" option. The "About" menu doesn't really need an index option since "Mission" already goes to the top of the landing page.
