### ISSUE TITLE
Investigate drop in WordPress representation

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#79]
Builtwith puts WordPress coverage at [~30%](https://trends.builtwith.com/cms/WordPress) of the web.

After increasing the coverage to 1.3M URLs from CrUX, we ~doubled the number of WordPress sites detected. However, the coverage increase was a factor of ~3x, so the relative percent of WordPress sites has gone down:

date | client | wordpress | total | %
-- | -- | -- | -- | --
Aug 1, 2018 | desktop | 201,474 | 1,275,374 | 15.80%
Aug 1, 2018 | mobile | 198,572 | 1,268,277 | 15.66%
Jul 15, 2018 | desktop | 201,277 | 1,277,631 | 15.75%
Jul 15, 2018 | mobile | 198,290 | 1,272,071 | 15.59%
Jul 1, 2018 | desktop | 200,927 | 1,277,805 | 15.72%
Jul 1, 2018 | mobile | 101,401 | 451,109 | 22.48%
Jun 15, 2018 | desktop | 103,768 | 461,068 | 22.51%
Jun 15, 2018 | mobile | 100,978 | 451,307 | 22.37%

Prior to the coverage increase, WordPress represented ~22% of the URLs. This is still well below the 30% figure which is widely regarded as the source of truth. After the expansion, WordPress representation dropped to ~16%.

In January 2018 @pmeenan ran an experiment where he tested all 2.9M CrUX URLs and detected WordPress on 785k (27%) of them. Assuming this ratio holds true in the most recent CrUX release that formed the basis of the HA corpus, we're not capturing (or detecting) a significant proportion of these sites.

The methodology behind the corpus change was to intersect the Alexa Top 1M domains (as of March 15, 2017) with origins in the 201805 CrUX release. We should investigate whether this approach introduced bias that excluded a significant proportion of WordPress sites.

**Comment by pmeenan** [comment]
The test I ran was pretty trivial and looked for /wp-content or /wp-includes anywhere in the html.  It probably generated a few false-positives but the Wappalyzer WordPress detection is also really week and I'm sure it generates far more false-negatives.  The Builtwith detection is considerably more robust.

I'd probably recommend starting by just looking at everything on wordpress.com and see if we detect 100% of them as WordPress and if not, improve the detection and send patches back to Wappalyzer.  Then move on to WPEngine and a few other well-known wordpress-only hosts and then see where we are.

Might not hurt to also add detection for all of the known template sites (they usually include some text in the templates).

**Comment by pmeenan** [comment]
Not the low-hanging fruit I was hoping for

________________________________

**Comment by igrigorik** [comment]
That's good news though :-)

@pmeenan do you still have the script you used for earlier crawl? Still wondering if we could run that against the current list (or some random sample of it), to see if we can spot any obvious faults that we may be overlooking here.

**Comment by igrigorik** [comment]
Hmm, I guess that's good news though. :-)

@rviscomi how does the distribution look if we simply scan for "/wp-content" or "/wp-includes"?

**Comment by rviscomi** [comment]
```sql
SELECT
  COUNT(DISTINCT page)
FROM
  `httparchive.response_bodies.2018_08_15_desktop`
WHERE
  body LIKE '%/wp-content%' OR
  body LIKE '%/wp-includes%'
```

406955 (32%) - now that's more like it! Bound to have more false positives but I'll investigate.

**Comment by rviscomi** [comment]
I manually confirmed that a few of those pages are using WordPress. For example:

- https://forbes.hu/
- http://dixie.edu/
- http://sleep.org/

I visited each page and used the Wappalyzer extension to verify the CMS.

The weird thing is that none of these sites are appearing in the `technologies` dataset:

```sql
SELECT
  *
FROM
  `httparchive.technologies.2018_08_15_desktop`
WHERE
  url IN ('https://forbes.hu/', 'http://dixie.edu/', 'http://sleep.org/')
```

The table for this particular crawl has technology info for 1,260,832 distinct URLs. That leaves 12,701 URLs with no tech info. Even if 100% of those missing are WordPress, that doesn't fully explain the discrepancy. Still, something else to look into. cc @pmeenan

**Comment by igrigorik** [comment]
Does the other data for those sites look reasonable? E.g. did we get an error page from them? Or, is it possible that the detection script failed to execute for some reason?

**Comment by pmeenan** [comment]
Awesome, thanks.  Failcases help.  I may not be able to look at it until this afternoon but if it is failing to run the script hopefully I can figure out why and also add a flag to the HAR so we can track how often it happens.

**Comment by pmeenan** [comment]
At least as of right now, all 3 of those are detecting as WordPress in WPT.  Looking to see if the crawl detected it at the test level or not.

**Comment by pmeenan** [comment]
Is something maybe wrong with the technologies data set?

I pulled forbes.hu and [here](https://httparchive.webpagetest.org/export.php?bodies=1&pretty=1&test=180801_J4_13DKH) is the HAR from the test:

```json
                "_detected": {
                    "Web Frameworks": "Bootstrap 3.2.0",
                    "Programming Languages": "PHP",
                    "Blogs": "WordPress",
                    "Miscellaneous": "Twitter Emoji (Twemoji)",
                    "Web Servers": "Nginx 1.12.2",
                    "Analytics": "Google Analytics Universal Analytics",
                    "JavaScript Libraries": "jQuery 1.12.4,jQuery Migrate 1.4.1",
                    "Databases": "MySQL",
                    "Widgets": "Facebook",
                    "Font Scripts": "Google Font API",
                    "CMS": "WordPress"
                },
                "_detected_apps": {
                    "jQuery": "1.12.4",
                    "Bootstrap": "3.2.0",
                    "Google Analytics": "Universal Analytics",
                    "jQuery Migrate": "1.4.1",
                    "Nginx": "1.12.2",
                    "Facebook": "",
                    "Google Font API": "",
                    "MySQL": "",
                    "WordPress": "",
                    "PHP": "",
                    "Twitter Emoji (Twemoji)": ""
                },
```

**Comment by pmeenan** [comment]
I think maybe something is going wrong with the HAR processing.  https://forbes.hu/ doesn't have the detected apps set in the HAR table.

```sql
#standardSQL
SELECT
  url, JSON_EXTRACT(payload, '$._detected') as detected
FROM
  `httparchive.pages.2018_08_15_desktop`
WHERE
  url = 'https://forbes.hu/';
```
Returns NULL (it returns WordPress for the 8/1 crawl).

The [raw har from the test result](https://httparchive.webpagetest.org/export.php?test=180815_J4_13DKH&run=3&cached=0&bodies=1&pretty=1) doesn't have the detected apps for run 3 (which was extracted for the HAR) but it does have it for run 1.

Looks like something is intermittently failing to get the Wappalyzer detections.

**Comment by pmeenan** [comment]
Sorry for the stream-of-consciousness.  I can reproduce it on my dev machine right now.  Doing some printf debugging to track down the cause within the Wappalyzer script (it's intermittently throwing an exception).

**Comment by pmeenan** [comment]
Not 100% sure yet - something with the async nature of Wappalyzer and interacting with Chrome dev tools API that sometimes it just doesn't seem to complete (I already poll for the async result).  I added a few redundancies that helped in the local repo case but it may still be racy.

I added a flag wappalyzer_failed = 1 to the page-level data to track failures so we'll be able to see how big of an issue it is next crawl.

If it continues to be an issue I can change the Wappalyzer detection to be Chrome-only and see about awaiting for the promises directly.

**Comment by pmeenan** [comment]
I sucked it up and Wappalyzer detection is now Chrome-only.  It deterministically awaits the async execution and promises and seems to be 100% reliable locally now.  We'll see how it looks in the Sept 15 crawl.

**Comment by igrigorik** [comment]
@pmeenan what do you mean by Chrome-only? Are you modifying the version we're using / does it mean we'll have to do extra work each time we want to update it?

**Comment by pmeenan** [comment]
WPT used to run wappalyzer for chrome and Firefox agents but the Firefox API doesn't have a good way to await an asynchronous script. Shouldn't be an issue for WPT (and certainly isn't for HA).

No extra work needed. It's the js wrapper around the engine and now uses async and await.

________________________________

**Comment by igrigorik** [comment]
Gotcha, awesome. Thanks for tracking this down Pat! 

Anything extra we need to do to push this out so it runs in next crawl?

**Comment by pmeenan** [comment]
Nope. Already pushed out and live across all WPT agents (public, HA and most private instances).

________________________________

**Comment by igrigorik** [comment]
Awesome, thanks Pat!

**Comment by rviscomi** [comment]
It's good we're fixing the raciness of the detection but I'm still skeptical about the large drop in WordPress sites. For example, Drupal detection retains a comparable percentage before/after the migration:

date | client | drupal | total | %
-- | -- | -- | -- | --
Aug 1, 2018 | desktop | 39,954 | 1,275,374 | 3.13%
Aug 1, 2018 | mobile | 39,490 | 1,268,277 | 3.11%
Jul 15, 2018 | desktop | 40,045 | 1,277,631 | 3.13%
Jul 15, 2018 | mobile | 39,579 | 1,272,071 | 3.11%
Jul 1, 2018 | desktop | 40,050 | 1,277,805 | 3.13%
Jul 1, 2018 | mobile | 14,624 | 451,109 | 3.24%
Jun 15, 2018 | desktop | 15,044 | 461,068 | 3.26%
Jun 15, 2018 | mobile | 14,611 | 451,307 | 3.24%

It actually decreased by 4%, but this is within reasonable limits. WordPress decreased by 30%. The race condition should apply equally to each kind of website, so that leads me to believe it's a WordPress-specific problem.

**Comment by pmeenan** [comment]
It's possible that the delta is specific to the migration and the issue always caused random sampling.  The fix should improve the accuracy of the overall total (i.e. Why WordPress is 15-20% instead of closer to 40%). 

More importantly, we now have an explicit flag for when Wappalyzer results weren't available so we'll understand failures to run vs detection failures.

**Comment by rviscomi** [comment]
Closing this issue. The full-CrUX desktop crawl now contains [about a million](https://wordpress.httparchive.org/reports/state-of-the-web#numUrls) WordPress pages out of [3.8M](https://httparchive.org/reports/state-of-the-web#numUrls) pages tested. This brings the representation to 26%, which is much much more realistic. I expect the mobile numbers to pick up when the 2019_01_01 crawl completes EOM.

![image](https://user-images.githubusercontent.com/1120896/50644496-04d5fd80-0f3f-11e9-84a3-8324742e6e2f.png)
