### ISSUE TITLE
Investigate drop in LoAF attribution data

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#817]
In the analytics for the httparchive.org website itself, the percentage of INP events having LoAF attribution data dropped at the end of last month:

<img width="591" alt="image" src="https://github.com/HTTPArchive/httparchive.org/assets/1120896/938e2014-3753-475b-9885-8c0d53497621">

```sql
SELECT
  event_date,
  COUNTIF(EXISTS(SELECT 1 FROM UNNEST(event_params) AS param WHERE STARTS_WITH(param.key, 'debug_loaf'))) AS nav_with_loaf,
  COUNT(0) AS nav_with_inp,
  COUNTIF(EXISTS(SELECT 1 FROM UNNEST(event_params) AS param WHERE STARTS_WITH(param.key, 'debug_loaf'))) / COUNT(0) AS pct_nav_with_loaf
FROM
  `httparchive.analytics_386559427.inp`
WHERE
  metric_name = 'INP' AND
  httparchive.analytics_386559427.FILTER_PREVIOUS_N_DAYS(event_date, 90, FALSE)
GROUP BY
  event_date
ORDER BY
  event_date
```

The lack of LoAF data makes it a lot harder to diagnose INP issues.

Possible issues:

- the API itself in Chrome (we're only logging for users with the experimental flag enabled)
- our origin trial registration
- our implementation/reporting
- our analysis

This could definitely be user error (me) but I wanted to file this issue as a reminder to investigate the reason.

FWIW I did take a quick look at the OT registration and it doesn't seem like it's expired or anything:

<img width="784" alt="image" src="https://github.com/HTTPArchive/httparchive.org/assets/1120896/9f306fc7-d4ce-4e56-8e1f-ba6a11c565d4">

It will actually expire on March 5, and it's not renewable at this point. The LoAF API doesn't reach stable until later in the month. So there's going to be a bit of a blackout. Hopefully we can figure out what's going on and get some data flowing before the expiration.

**Comment by tunetheweb** [comment]
Have you considered the possibility that your solution means there's less long frames to report now because there is no long frames/tasks anymore?

**Comment by rviscomi** [comment]
It seems like one instance of `desiredExecutionStart` was left in the code as part of the `totalDuration` calculation:

```js
const totalDuration = script.startTime + script.duration - script.desiredExecutionStart;
if (totalDuration > loafAttribution.debug_loaf_script_total_duration) {
```

Since the property was removed from the API, we were subtracting `undefined` from a number, which resulted in `NaN`.

Then in the check for whether to go on with the rest of the LoAF attribution, we were trying to evaluate `NaN > 0` which is always false, so we never got any LoAF info.

To explain why we still sometimes got LoAF data in the analytics, users must have been on older versions of Chrome that weren't affected by the property removals.
