### ISSUE TITLE
Widen default time selection

### ISSUE THREAD

**Issue by paulirish** [HTTPArchive/httparchive.org#82]
On pages like https://httparchive.org/reports/state-of-javascript the default time shown in the big chart is... the past 12 months? But then the time selector beneath is about 9 times wider. Could the UI default to showing 50% of the available data?  (or in the case of some newer reports, no less than 2 years?)

wdyt

**Comment by rviscomi** [comment]
The config form at the top of the report shows the start/end dates, which you're right is 12 months by default.

Many but not all metrics have 8 years of historical data, so if we make it 50% of available data by default, metrics within the same report may have different time spans.

I'm leaning towards keeping the time span consistent, eg so users know that the +/- % change stats are always 1 year by default.

![image](https://user-images.githubusercontent.com/1120896/45243076-7dde8480-b2c0-11e8-929b-bb0e8d106cfc.png)

**Comment by paulirish** [comment]
ahh. then actually what i'm asking is.. 

_What about lengthening the default start/end dates in the confirm form?_

If we went to 3 years, I suppose loading-speed would have different time spans on the same page. But even so, there were and are (progressive-web-apps) pages that had this issue already.  

Admittedly I dont know a perfect solution since the data is all of different ages. Just throwing it out there that i suspect most people turn to HA for macro trends and I don't think a 12mo default really demonstrates the value of HA's data as well as it could.

**Comment by rviscomi** [comment]
Ah ok, yeah I'd be ok changing it to 3 years.

**Comment by rafaelcastrocouto** [comment]
I guess you need to change this value: https://github.com/HTTPArchive/httparchive.org/blob/master/main.py#L156

**Comment by rviscomi** [comment]
@rafaelcastrocouto yes, that's it

**Comment by rafaelcastrocouto** [comment]
Ok, I've changed the value from 24 to 72 and created the pull request linked above.

I'm wondering if it would be a good idea to move this value inside reports.json file metrics

https://github.com/HTTPArchive/httparchive.org/blob/master/config/reports.json

**Comment by rviscomi** [comment]
@rafaelcastrocouto reports.json can be used for report-specific overrides but main.py is the best place for the global default. thanks for working on this!
