### ISSUE TITLE
Old version of web-vitals.js in production

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#822]
Despite our [package.json](https://github.com/HTTPArchive/httparchive.org/blob/5ecb92d67d115f61c732e38a93a976903239375c/package.json#L40) being up to date on version 3.5.2, [web-vitals.js in production](https://httparchive.org/static/js/web-vitals.js) has stale code:

<img width="1007" alt="image" src="https://github.com/HTTPArchive/httparchive.org/assets/1120896/35466a88-00d4-4c93-9fe1-acfca717d441">

It's missing the [`firstEntryWithTarget`](https://github.com/GoogleChrome/web-vitals/blob/main/src/attribution/onINP.ts#L45) fix for INP attribution:

<img width="623" alt="image" src="https://github.com/HTTPArchive/httparchive.org/assets/1120896/abcb2a6c-e3cd-4fb2-939b-0758282660da">

I noticed this while debugging INP in production and seeing discrepancies between the Web Vitals extension (which is actually on 3.5.2) and the script we're using for our RUM:

![image](https://github.com/HTTPArchive/httparchive.org/assets/1120896/f44ec6f9-7fc3-4cee-90a8-8659b66b6488)

This is causing our INP analysis to miss some valuable attribution info.

It seems like the [`generate` script](https://github.com/HTTPArchive/httparchive.org/blob/5ecb92d67d115f61c732e38a93a976903239375c/tools/generate/generate_js.js#L20-L24) responsible for moving the web-vitals.js code from `node_modules` to `static/js/` doesn't run as part of the pre-deploy action nor the `deploy` script.

**Comment by rviscomi** [comment]
Hmm I take that back. [`run_and_test_website.sh`](https://github.com/HTTPArchive/httparchive.org/blob/5ecb92d67d115f61c732e38a93a976903239375c/tools/scripts/run_and_test_website.sh#L65) which is part of the pre-deploy action should run the `generate` script. Now I wonder why didn't it update.

**Comment by rviscomi** [comment]
We upgraded to version 3.5.2 as part of https://github.com/HTTPArchive/httparchive.org/pull/802. The next predeploy script was https://github.com/HTTPArchive/httparchive.org/pull/804, but it only contained the timestamp updates and not the web-vitals.js changes.

**Comment by rviscomi** [comment]
Oh! The `generate` script moves the new version into `static/js` which is in our [.gitignore](https://github.com/HTTPArchive/httparchive.org/blob/5ecb92d67d115f61c732e38a93a976903239375c/.gitignore#L5) file, so it never gets included in the PRs.

**Comment by tunetheweb** [comment]
> We upgraded to version 3.5.2 as part of https://github.com/HTTPArchive/httparchive.org/pull/802. The next predeploy script was https://github.com/HTTPArchive/httparchive.org/pull/804, but it only contained the timestamp updates and not the web-vitals.js changes.

That's correct. We don't store the generated JS in git (note it's not here: https://github.com/HTTPArchive/httparchive.org/tree/main/static).

But it should be generated locally as part of the deploy process and then pushed to prod. As part of `npm run deploy`.

**Comment by rviscomi** [comment]
I know that for the past couple of deploys I did, the deployment script [started up a local web server](https://github.com/HTTPArchive/httparchive.org/blob/main/tools/scripts/run_and_test_website.sh#L54C1-L54C28) and then stopped running. So I just manually pushed it with `gcloud app deploy` at that point, apparently skipping the build/generate/test steps.

@tunetheweb do you remember if your deployment after https://github.com/HTTPArchive/httparchive.org/pull/804 ran normally?

**Comment by tunetheweb** [comment]
Always does! :-)

I've just re-deployed and it's there now: https://httparchive.org/static/js/web-vitals.js?test=123456

I suspect you deployed without running `npm run generate` and so uploaded an old copy and overwrote my previous (successful!) deploy :-)

**Comment by tunetheweb** [comment]
Here's the January 28th deploy and it's the correct version: https://20240128t130208-dot-httparchive.uk.r.appspot.com/static/js/web-vitals.js?test=123456

**Comment by rviscomi** [comment]
Nice ok so I should figure out why the deployment script craps out for me, or maybe we should move the install/build/generate steps before starting the server?

**Comment by rviscomi** [comment]
With https://github.com/HTTPArchive/httparchive.org/pull/823 merged and the latest version deployed I think we can close this. Thanks for your help tracking it down @tunetheweb!
