### ISSUE TITLE
PWA score data ends in May 2018

### ISSUE THREAD

**Issue by paulirish** [HTTPArchive/httparchive.org#83]
just noticed it https://httparchive.org/reports/progressive-web-apps#pwaScores

and [js bootup's last data](https://httparchive.org/reports/loading-speed?view=list#bootupJs) is jul15 rather than aug15

**Comment by rviscomi** [comment]
Assigning to Tom to investigate.

The [query](https://raw.githubusercontent.com/HTTPArchive/bigquery/master/sql/timeseries/pwaScores.sql) looks for `$.reportCategories.find(i => i.name === 'Progressive Web App').score` which may have changed in 3.0.

**Comment by paulirish** [comment]
yup that changed.

`$.categories.pwa.score` should do the trick.

**Comment by tomayac** [comment]
Thanks for the report, @paulirish. I will have a look after the perf period is over…
