### ISSUE TITLE
Beta Report - Confusion about where the data is

### ISSUE THREAD

**Issue by jordyscholing** [HTTPArchive/httparchive.org#851]
I didn't know where to look after I changed the field and pressed "update". Since it is still in beta I didn't think much of it as data might not work yet. Turned out I had to scroll down. Maybe indicate or somehow make it clearer that the data is below the fold.
![image](https://github.com/HTTPArchive/httparchive.org/assets/163306795/1dff015a-43fb-4137-b3df-fc9c325e0021)

This is especially something for the "comparison" tab, as there are more input fields and you don't see that there's something below the fold directly. On the "drilldown" tab you have some kind of indication: 
![image](https://github.com/HTTPArchive/httparchive.org/assets/163306795/a93eea01-478b-4961-94b2-69277ff10121)

**Comment by tunetheweb** [comment]
Maybe we should scroll down to the chart after clicking Update button?

**Comment by jordyscholing** [comment]
> Maybe we should scroll down to the chart after clicking Update button?

Yeh, sounds good to me :)
