### ISSUE TITLE
Improve tech report page weight formatting

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#853]
<img width="1166" alt="image" src="https://github.com/HTTPArchive/httparchive.org/assets/1120896/8da61f0c-4852-43ec-97a7-409eb8f7aaca">

In this screenshot the image weight is shown as "752149 kB"

This seems to be showing the number of bytes, not KB. Let's convert from bytes to KB and if the value is still larger than 1000, convert again from KB to MB. Round to the nearest whole value to avoid showing any decimal places.

Also, as in the existing [Page Weight report](https://httparchive.org/reports/page-weight#bytesTotal) we typically format the unit as capital-K "KB":

<img width="520" alt="image" src="https://github.com/HTTPArchive/httparchive.org/assets/1120896/2ac5a8e3-552e-4573-90ae-36c2480e3d45">

**Comment by tunetheweb** [comment]
Relevant: https://github.com/HTTPArchive/httparchive.org/issues/643
