### ISSUE TITLE
Reports not showing up on mobile

### ISSUE THREAD

**Issue by WellingGuzman** [HTTPArchive/httparchive.org#86]
I tried using Brave, Firefox and Safari and none of them shows the reports.

See screenshot: 

![](https://user-images.githubusercontent.com/1531291/45266132-2b1ddd80-b424-11e8-8df7-a51f95be810e.PNG)

Using safari I could find the logs and the browser can't find the `fetch` function.

<img width="1001" src="https://user-images.githubusercontent.com/1531291/45266149-5a344f00-b424-11e8-9de5-90131b09ccf9.png">

I could add more details if it is necessary.

**Comment by rviscomi** [comment]
Weird. Fetch should be supported in Safari https://caniuse.com/#feat=fetch

URLSearchParams doesn't seem to be supported in Safari: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#Browser_compatibility

No idea what's wrong in Firefox. Any more you could share to debug it?

**Comment by WellingGuzman** [comment]
I see this may be due to my old OS.

Extra information:
- iOS 10.2
- iOS Google Chrome 63.0.3239.73
- Brave 1.5.2 (17.12.12.15)

It makes sense for Safari Mobile, but it didn't worked for neither chrome or brave.

I tried with safari on iOS 11.4.1 and it works. I may call this bug on older browser, I don't know this is something you want to follow

**Comment by WellingGuzman** [comment]
I have no way to debug any other browser than Safari, but this is the details I got of my Chrome from whatsmybrowser.org

<img width="750" src="https://user-images.githubusercontent.com/1531291/45589965-e18a3280-b8fc-11e8-9ffa-d5f3b896c4c4.png">

If this isn't helpful I am out of options, unless you know how can I debug this.

**Comment by WellingGuzman** [comment]
I have no way to debug any other browser than Safari, but this is the details I got of my Chrome from whatsmybrowser.org

<img width="750" src="https://user-images.githubusercontent.com/1531291/45590003-d1bf1e00-b8fd-11e8-9344-a088614539e4.png">


If this isn't helpful I am out of options, unless you know how can I debug this.

**Comment by rviscomi** [comment]
Unable to reproduce the issue
