### ISSUE TITLE
Allow local building without gcloud

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#87]
Authenticating with Google Cloud is necessary to call the storage APIs that tell us which dates are available for reports. When building the website locally, it should be possible to skip this requirement and get a truly static/deterministic environment. This can be with a non-default build flag or something.

**Comment by voidpirate** [comment]
Implemented in https://github.com/HTTPArchive/httparchive.org/pull/104, should be safe to close out this issue :)
