### ISSUE TITLE
_adult_site is false for everything since 2016 something

### ISSUE THREAD

**Issue by zcorpan** [HTTPArchive/httparchive.org#90]
```
SELECT
  url
FROM
  [httparchive:summary_pages.2018_06_15_desktop]
WHERE
  _adult_site IS TRUE
```
0 results.
```
SELECT
  url
FROM
  [httparchive:summary_pages.2017_06_15_desktop]
WHERE
  _adult_site IS TRUE
```
0 results.
```
SELECT
  url
FROM
  [httparchive:summary_pages.2016_06_15_desktop]
WHERE
  _adult_site IS TRUE
```
7071 results.

**Comment by rviscomi** [comment]
Not sure where this flag gets set but it's not something we support in the new CrUX-based dataset of URLs.

**Comment by rviscomi** [comment]
Yeah we just don't have the data for this anymore. It may have been something provided by old versions of the Alexa list, but it's not available especially now that we've moved away from Alexa and onto the CrUX dataset.
