### ISSUE TITLE
Technology data smaller than previous months

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/httparchive.org#919]
https://lookerstudio.google.com/reporting/1jh_ScPlCIbSYTf2r2Y6EftqmX9SQy4Gn/page/2JBdB

<img width="770" alt="image" src="https://github.com/user-attachments/assets/6f7c6161-d473-48aa-8eef-40b50d47684e">

[Investigating the data](https://docs.google.com/spreadsheets/d/18sfhlLU73Napvk0jWAaZ_9xpcBnodOsRYBZbxtcZnRI/edit?gid=1205340876#gid=1205340876) it looks like WebMail, Email, Hosting, and CRM are some of those most affected.

And looking at the first 2 it looks like Wappalzyer uses MX DNS records for those and for the others SOA DNS records can be used.

@pmeenan you said you changed some of the DNS lookups so might know what's caused this?

**Comment by tunetheweb** [comment]
Looks like NS and TXT records are also used by Wappalyzer.

**Comment by pmeenan** [comment]
Looks like when I changed the metrics collection to run in parallel, wappalyzer relied on one of those metrics to see what the document hostname was (to do the DNS lookups). Should be a quick fix to get the hostname synchronously first if it isn't set yet.
