### ISSUE TITLE
Kinsta detection issues

### ISSUE THREAD

**Issue by avatarf** [HTTPArchive/httparchive.org#961]
[Kinsta](https://kinsta.com/) is missing from the [new beta dashboard](https://httparchive.org/reports/techreport/comparison?categories=ALL&categories=Hosting&categories=ALL&categories=ALL&tech=Bluehost%2CWP+Engine%2CHostgator%2CGoDaddy%2CIONOS%2CSiteGround&geo=United+States+of+America&rank=ALL&median-lighthouse-over-time=best_practices&good-cwv-over-time=INP#report-content), it is not even possible to select it from the technology dropdown.

It was available on the previous dashboard.
![Image](https://github.com/user-attachments/assets/e4f29f48-c524-4e13-a5ff-a9a5bdcd612e)

I couldn't check the codebase yet, but in the [technologies/k.json](https://github.com/HTTPArchive/wappalyzer/blob/603be50ecc9034ad3f13f74638f4d1fa84577294/src/technologies/k.json#L707), Kinsta is still available.

**Comment by tunetheweb** [comment]
We discovered this was due to a missing Description in the definition in [technologies/k.json](https://github.com/HTTPArchive/wappalyzer/blob/603be50ecc9034ad3f13f74638f4d1fa84577294/src/technologies/k.json#L707). We'll make it non-mandatory in future but would be good if we could add a description anyway. Could you suggest one @avatarf ?

**Comment by avatarf** [comment]
I see 👍
I suggest: "Kinsta is a leading managed WordPress hosting provider, prioritizing speed and security."


ps.: To clarify, I am affiliated with Kinsta and 100% in love with our service 😄. 
Yet, if a more simplified/standard description is preferred, I've noticed that some other similar providers simply describe themselves as "XYZ is a website hosting provider." That description works as well.

**Comment by tunetheweb** [comment]
Fixed in: https://github.com/HTTPArchive/wappalyzer/pull/76
